CREATE DATABASE grubal
GO
USE [grubal]
GO
/****** Object:  Schema [DOCUMENTO]    Script Date: 7/8/2020 8:40:40 PM ******/
CREATE SCHEMA [DOCUMENTO]
GO
/****** Object:  Schema [INVENTARIO]    Script Date: 7/8/2020 8:40:40 PM ******/
CREATE SCHEMA [INVENTARIO]
GO
/****** Object:  Schema [MARKETING]    Script Date: 7/8/2020 8:40:40 PM ******/
CREATE SCHEMA [MARKETING]
GO
/****** Object:  Schema [PERSONA]    Script Date: 7/8/2020 8:40:40 PM ******/
CREATE SCHEMA [PERSONA]
GO
/****** Object:  Schema [PROYECTO]    Script Date: 7/8/2020 8:40:40 PM ******/
CREATE SCHEMA [PROYECTO]
GO
/****** Object:  Schema [VENTA]    Script Date: 7/8/2020 8:40:40 PM ******/
CREATE SCHEMA [VENTA]
GO
/****** Object:  Table [PERSONA].[TELEFONO]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PERSONA].[TELEFONO](
	[id_telefono] [int] IDENTITY(1,1) NOT NULL,
	[tipo_telefono] [tinyint] NOT NULL,
	[id_persona] [int] NOT NULL,
	[codigo_pais] [varchar](5) NOT NULL,
	[campo_1] [varchar](5) NOT NULL,
	[campo_2] [varchar](5) NOT NULL,
	[campo_3] [varchar](5) NOT NULL,
	[ext] [varchar](5) NULL,
 CONSTRAINT [PK__TELEFONO_bf60e690] PRIMARY KEY CLUSTERED 
(
	[id_telefono] ASC,
	[tipo_telefono] ASC,
	[id_persona] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [PERSONA].[EMAIL]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PERSONA].[EMAIL](
	[id_email] [int] IDENTITY(1,1) NOT NULL,
	[tipo_email] [tinyint] NOT NULL,
	[id_persona] [int] NOT NULL,
	[direccion_email] [varchar](320) NOT NULL,
 CONSTRAINT [PK__EMAIL_988a67b5] PRIMARY KEY CLUSTERED 
(
	[id_email] ASC,
	[tipo_email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [INVENTARIO].[ARTICULO]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [INVENTARIO].[ARTICULO](
	[id_item] [int] IDENTITY(1,1) NOT NULL,
	[nom_articulo] [varchar](99) NULL,
	[marca_articulo] [varchar](99) NULL,
	[descripcion_articulo] [varchar](500) NULL,
	[unidad_medida_articulo] [varchar](32) NULL,
	[valor_unitario] [money] NULL,
	[unidades_disponibles] [int] NULL,
	[id_proveedor] [int] NULL,
 CONSTRAINT [PK__ARTICULO__7934a197] PRIMARY KEY CLUSTERED 
(
	[id_item] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 94) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [PERSONA].[SALARIO]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PERSONA].[SALARIO](
	[id_persona] [int] NOT NULL,
	[id_salario] [int] IDENTITY(1,1) NOT NULL,
	[monto] [money] NOT NULL,
	[frequencia_de_pago_dias] [tinyint] NOT NULL,
	[fecha_modificada] [datetime] NOT NULL,
 CONSTRAINT [PK__SALARIO_7cececbd] PRIMARY KEY CLUSTERED 
(
	[id_persona] ASC,
	[id_salario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [PERSONA].[EMAIL_TIPOS]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PERSONA].[EMAIL_TIPOS](
	[tipo_email] [tinyint] IDENTITY(1,1) NOT NULL,
	[nombre_email] [varchar](50) NOT NULL,
 CONSTRAINT [PK__TIPO_EMAIL_ffea2749] PRIMARY KEY CLUSTERED 
(
	[tipo_email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [PERSONA].[ID_PERSONA]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PERSONA].[ID_PERSONA](
	[id_persona] [int] IDENTITY(1,1) NOT NULL,
	[uid] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK__ID_PERSONA_05a49598] PRIMARY KEY CLUSTERED 
(
	[id_persona] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 87) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[TIPO DE EMAIL DE LA PERSONA 230]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- MOSTRAR EL TIPO DE EMAIL DE LA PERSONA 230
CREATE VIEW [dbo].[TIPO DE EMAIL DE LA PERSONA 230] AS
SELECT A.id_persona AS [ ID PERSONA] , 
	C.tipo_email AS [TIPO DE EMAIL],
	C.nombre_email AS [NOMBRE DEL TIPO EMAIL]
FROM PERSONA.ID_PERSONA A 
INNER JOIN PERSONA.EMAIL B ON A.id_persona=B.id_persona
INNER JOIN PERSONA.EMAIL_TIPOS C ON B.tipo_email=C.tipo_email
WHERE A.id_persona = 230
GO
/****** Object:  Table [DOCUMENTO].[COTIZACION]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [DOCUMENTO].[COTIZACION](
	[id_documento] [int] NOT NULL,
	[id_proyecto] [int] NOT NULL,
	[id_encargado] [int] NOT NULL,
	[id_aprobado_por] [int] NULL,
	[enviar_a] [int] NULL,
	[fecha_aprobacion] [datetime] NULL,
	[fecha_creacion] [datetime] NOT NULL,
	[fecha_envio] [datetime] NULL,
	[valor_total] [money] NOT NULL,
	[notas] [varchar](1024) NULL,
	[path_archivo] [varchar](256) NOT NULL,
 CONSTRAINT [PK__COTIZACION_f0d5954e] PRIMARY KEY CLUSTERED 
(
	[id_documento] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [PERSONA].[CLIENTE]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PERSONA].[CLIENTE](
	[id_persona] [int] NOT NULL,
	[marketing] [int] NOT NULL,
	[nom_cliente] [varchar](200) NOT NULL,
	[doc_oficial] [varchar](16) NOT NULL,
 CONSTRAINT [PK__CLIENTE_cce807bf] PRIMARY KEY CLUSTERED 
(
	[id_persona] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [PROYECTO].[PROYECTO]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PROYECTO].[PROYECTO](
	[id_proyecto] [int] IDENTITY(1,1) NOT NULL,
	[id_cliente] [int] NOT NULL,
	[id_division] [tinyint] NOT NULL,
	[nom_proyecto] [varchar](99) NULL,
	[dir_proyecto] [nvarchar](99) NULL,
	[fecha_inicio] [date] NULL,
	[fecha_fin] [date] NULL,
 CONSTRAINT [PK__PROYECTO_2a578b7b] PRIMARY KEY CLUSTERED 
(
	[id_proyecto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[COTIZACIONES DEL CLIENTE 420]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- MOSTRAR LAS COTIZACIONES DE LA PERSONA CLIENTE NUMERO 420
CREATE VIEW [dbo].[COTIZACIONES DEL CLIENTE 420] AS
SELECT 
	A.valor_total AS [VALOR TOTAL],
	B.nom_proyecto AS [NOMBRE DEL PROYECTO],
	C.nom_cliente AS [NOMBRE DEL CLIENTE],
	C.id_persona AS [CODIGO DEL CLIENTE]
FROM DOCUMENTO.COTIZACION A
INNER JOIN PROYECTO.PROYECTO B ON A.id_proyecto=B.id_proyecto
INNER JOIN PERSONA.CLIENTE C ON B.id_cliente=C.id_persona
WHERE C.id_persona = 420
GO
/****** Object:  Table [PERSONA].[EMPLEADO]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PERSONA].[EMPLEADO](
	[id_persona] [int] NOT NULL,
	[puesto_empleado] [smallint] NOT NULL,
	[doc_oficial] [char](8) NOT NULL,
	[ruc_empleado] [char](11) NOT NULL,
	[fecha_nacimiento] [date] NOT NULL,
	[fecha_inicio] [date] NOT NULL,
	[primer_nom] [varchar](50) NOT NULL,
	[segundo_nom] [varchar](50) NULL,
	[primer_ape] [varchar](50) NOT NULL,
	[segundo_ape] [varchar](50) NOT NULL,
	[estado] [bit] NULL,
 CONSTRAINT [PK__EMPLEADO_b2867755] PRIMARY KEY CLUSTERED 
(
	[id_persona] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [VENTA].[ORDEN]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [VENTA].[ORDEN](
	[id_orden] [int] IDENTITY(1,1) NOT NULL,
	[id_proyecto] [int] NOT NULL,
	[id_cliente] [int] NOT NULL,
	[id_vendedor] [int] NOT NULL,
	[factura] [bit] NOT NULL,
	[notas] [varchar](500) NULL,
	[sub_total] [money] NOT NULL,
	[total_igv] [money] NOT NULL,
	[total_venta] [money] NOT NULL,
 CONSTRAINT [PK__ORDEN_51693179] PRIMARY KEY CLUSTERED 
(
	[id_orden] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [VENTA].[DETALLE_DE_ORDEN]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [VENTA].[DETALLE_DE_ORDEN](
	[id_orden] [int] NOT NULL,
	[id_detalle_orden] [uniqueidentifier] NOT NULL,
	[id_item] [int] NOT NULL,
	[cantidad] [int] NOT NULL,
	[precio_unitario] [money] NOT NULL,
	[descuento_unitario_prcnt] [money] NOT NULL,
	[precio_total_unidades] [money] NOT NULL,
 CONSTRAINT [PK__DETALLE_DE_ORDEN_60ad2cc0] PRIMARY KEY CLUSTERED 
(
	[id_orden] ASC,
	[id_detalle_orden] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 73) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[VENTAS DEL EMPLEADO 2]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- MOSTRAR LA VENTAS DEL EMPLEADO 2
CREATE VIEW [dbo].[VENTAS DEL EMPLEADO 2] AS
SELECT TOP 100 PERCENT
	A.primer_nom AS [NOMBRE],
	A.primer_ape AS [APELLIDO],
	A.id_persona AS [CODIGO DE EMPLEADO],
	B.id_orden AS [CODIGO DE ORDEN],
	C.cantidad AS [CANTIDAD]
FROM PERSONA.EMPLEADO A
INNER JOIN VENTA.ORDEN B ON A.id_persona=B.id_vendedor
INNER JOIN VENTA.DETALLE_DE_ORDEN C ON B.id_orden=C.id_orden
WHERE A.id_persona = 2
ORDER BY 1 DESC
GO
/****** Object:  View [dbo].[SALARIO DEL EMPLEADO 3]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


-- MOSTRAR EL SALARIO DE LA PERSONA EMPLEADO 3
CREATE VIEW [dbo].[SALARIO DEL EMPLEADO 3] AS
SELECT TOP 100 PERCENT
	A.primer_nom AS [NOMBRE],
	A.primer_ape AS [APELLIDO],
	A.id_persona AS [CODIGO DEL LA PERSONA EMPLEADO],
	B.monto AS [SALARIO]
FROM PERSONA.EMPLEADO A
INNER JOIN PERSONA.SALARIO B ON A.id_persona=B.id_persona
WHERE A.id_persona = 3
ORDER BY 1 DESC
GO
/****** Object:  View [dbo].[EMPLEADOS POR PROYECTO]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- MOSTRAR EL NOMBRE DEL PROYECTO POR CADA EMPLEADO
CREATE VIEW [dbo].[EMPLEADOS POR PROYECTO] AS
SELECT 
	A.primer_nom AS [NOMBRE],
	A.primer_ape AS [APELLIDO],
	C.nom_proyecto AS [NOMBRE DEL PROYECTO]
FROM
PERSONA.EMPLEADO A 
INNER JOIN VENTA.ORDEN B ON A.id_persona=B.id_vendedor
INNER JOIN PROYECTO.PROYECTO C ON B.id_proyecto=C.id_proyecto
GO
/****** Object:  View [dbo].[VENTAS POR VENDEDOR]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


--MONTO DE VENTAS POR VENDEDOR
CREATE VIEW [dbo].[VENTAS POR VENDEDOR] AS 
SELECT TOP 100 PERCENT
	id_vendedor AS [ID VENDEDOR],
	ROUND(SUM(total_venta), 2) AS [MONTO DE VENTAS]
FROM VENTA.ORDEN
GROUP BY id_vendedor
ORDER BY 2 DESC
GO
/****** Object:  View [dbo].[MEJORES CLIENTES]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--MEJORES 10 CLIENTES
CREATE VIEW [dbo].[MEJORES CLIENTES] AS
SELECT TOP 10 WITH TIES
	id_cliente AS [ID CLIENTE],
	'S./ ' + CAST(ROUND(SUM(total_venta), 2)AS VARCHAR) AS [MONTO DE VENTAS]
FROM VENTA.ORDEN
GROUP BY id_cliente
ORDER BY 2 DESC
GO
/****** Object:  Table [PERSONA].[PUESTO]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PERSONA].[PUESTO](
	[id_puesto] [smallint] IDENTITY(1,1) NOT NULL,
	[desc_puesto] [varchar](50) NOT NULL,
 CONSTRAINT [PK__PUESTO_f54c2885] PRIMARY KEY CLUSTERED 
(
	[id_puesto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[PLANILLA]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- MOSTRAR NOMBRES, PUESTOS Y SALARIOS DE PERSONAS EN PLANILLA
CREATE VIEW [dbo].[PLANILLA] AS 
SELECT  
	B.primer_nom + ' ' + B.primer_ape AS [NOMBRE],
	C.desc_puesto AS [PUESTO],
	A.monto AS [SALARIO],
	A.frequencia_de_pago_dias AS [FREQUENCIA DE PAGOS POR DIA]
FROM PERSONA.SALARIO A
INNER JOIN PERSONA.EMPLEADO B ON A.id_persona=B.id_persona
INNER JOIN PERSONA.PUESTO C ON B.puesto_empleado=C.id_puesto
GO
/****** Object:  View [dbo].[COTIZACIONES PROYECTO 784]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- MOSTRAR LAS COTIZACIONES DEL PROYECTO "784", NOMBRE DEL PROYECTO, ID DEL DOCUMENTO, QUIEN LO APROBO, MONTO Y FECHA DE ENVIO
-- ORDENAR POR MONTO TOTAL, REDONDEAR MONTO A 2 DECIMALES
CREATE VIEW [dbo].[COTIZACIONES PROYECTO 784] AS
SELECT TOP 100 PERCENT
	A.nom_proyecto AS [PROYECTO],
	B.id_documento AS [ID DOCUMENTO],
	C.primer_nom + ' ' + C.primer_ape AS [APROBADO POR],
	'S./ ' + CAST(ROUND(B.valor_total, 2) AS VARCHAR)  AS [MONTO TOTAL],
	B.fecha_envio AS [FECHA DE ENVIO]
FROM PROYECTO.PROYECTO A
INNER JOIN DOCUMENTO.COTIZACION B ON A.id_proyecto=B.id_proyecto
INNER JOIN PERSONA.EMPLEADO C ON B.id_aprobado_por=C.id_persona
WHERE A.id_proyecto = 784
ORDER BY 5 DESC
GO
/****** Object:  Table [MARKETING].[ENVIO]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MARKETING].[ENVIO](
	[id_envio] [int] IDENTITY(1,1) NOT NULL,
	[id_recividor] [int] NOT NULL,
	[id_ficha_marketing] [int] NOT NULL,
	[id_enviador] [int] NOT NULL,
	[presentacion_enviada] [smallint] NOT NULL,
	[fecha] [datetime] NOT NULL,
 CONSTRAINT [PK__MARKETING_4s6f8w9s] PRIMARY KEY CLUSTERED 
(
	[id_envio] ASC,
	[id_recividor] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 84) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [MARKETING].[ENVIABLE]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MARKETING].[ENVIABLE](
	[id_presentacion] [smallint] IDENTITY(1,1) NOT NULL,
	[descripcion_presentacion] [nvarchar](99) NOT NULL,
	[path_presentacion] [nvarchar](256) NOT NULL,
 CONSTRAINT [PK__MARKETING_5f4d9w2s] PRIMARY KEY CLUSTERED 
(
	[id_presentacion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[PRESENTACIONES ENVIADAS A 357]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- MOSTRAR LAS PRESENTACIONES ENVIADAS A EL CLIENTE "357"
CREATE VIEW [dbo].[PRESENTACIONES ENVIADAS A 357] AS
SELECT TOP 100 PERCENT
	A.descripcion_presentacion AS [NOMBRE PRESENTACION],
	B.fecha AS [FECHA DE ENVIO],
	C.nom_cliente AS [NOMBRE DEL CLIENTE]
FROM MARKETING.ENVIABLE A
INNER JOIN MARKETING.ENVIO B ON A.id_presentacion=B.presentacion_enviada
INNER JOIN PERSONA.CLIENTE C ON B.id_recividor=C.id_persona
WHERE B.id_recividor = 357
ORDER BY 2 ASC
GO
/****** Object:  Table [INVENTARIO].[PROVEEDOR]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [INVENTARIO].[PROVEEDOR](
	[id_proveedor] [int] IDENTITY(1,1) NOT NULL,
	[especialidad_proveedor] [int] NULL,
	[pais_proveedor] [tinyint] NULL,
	[nom_proveedor] [nvarchar](99) NULL,
 CONSTRAINT [PK__PROVEEDOR_320f0532] PRIMARY KEY CLUSTERED 
(
	[id_proveedor] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [PERSONA].[DIRECCION_PAIS]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PERSONA].[DIRECCION_PAIS](
	[id_pais] [tinyint] IDENTITY(1,1) NOT NULL,
	[nom_pais] [varchar](50) NOT NULL,
	[abr_pais] [char](2) NOT NULL,
 CONSTRAINT [PK__PAIS_89d3f635] PRIMARY KEY CLUSTERED 
(
	[id_pais] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[VENTAS DE PROVEEDORES EXTRANJEROS]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--MOSTRAR IDS DE VENTAS DONDE SE VENTIERON PRODUCTOS DE PROVEDORES EXTRANJEROS
CREATE VIEW [dbo].[VENTAS DE PROVEEDORES EXTRANJEROS] AS 
SELECT 
	E.id_orden AS [ID ORDEN],
	B.pais_proveedor AS [CODIGO PAIS],
	A.nom_pais AS [NOMBRE PAIS]
FROM PERSONA.DIRECCION_PAIS A
INNER JOIN INVENTARIO.PROVEEDOR B ON A.id_pais=B.pais_proveedor
INNER JOIN INVENTARIO.ARTICULO C ON B.id_proveedor=C.id_proveedor
INNER JOIN VENTA.DETALLE_DE_ORDEN D ON C.id_item=D.id_item
INNER JOIN VENTA.ORDEN E ON D.id_orden=E.id_orden
WHERE B.pais_proveedor NOT IN(1, 168)
GO
/****** Object:  View [dbo].[MONTO VENDIDO POR CLIENTE]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--MONTO DE VENTAS POR CLIENTE
CREATE VIEW [dbo].[MONTO VENDIDO POR CLIENTE] AS
SELECT TOP 100 PERCENT
	id_cliente AS [ID CLIENTE],
	'S./ ' + CAST(ROUND(SUM(total_venta), 2) AS VARCHAR)  AS [MONTO DE VENTAS]
FROM VENTA.ORDEN
GROUP BY id_cliente
ORDER BY 2 DESC
GO
/****** Object:  View [dbo].[VENTAS POR PROYECTO]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--MONTO DE VENTAS POR PROYECTO
CREATE VIEW [dbo].[VENTAS POR PROYECTO] AS
SELECT TOP 100 PERCENT
	id_proyecto AS [ID PROYECTO],
	'S./ ' + CAST(ROUND(SUM(total_venta), 2) AS VARCHAR) AS [MONTO DE VENTAS]
FROM VENTA.ORDEN
GROUP BY id_proyecto
ORDER BY 2 DESC
GO
/****** Object:  View [dbo].[MEJORES PROYECTOS]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


--MEJORES 10 PROYECTOS CON MAYORES VENTAS
CREATE VIEW [dbo].[MEJORES PROYECTOS] AS
SELECT TOP 10 WITH TIES
	id_proyecto AS [ID PROYECTO],
	'S./ ' + CAST(ROUND(SUM(total_venta), 2) AS VARCHAR) AS [MONTO DE VENTAS]
FROM VENTA.ORDEN
GROUP BY id_proyecto
ORDER BY 2 DESC
GO
/****** Object:  View [dbo].[ARTICULOS EN STOCK]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--NOMBRE DE ARTICULO POR CANTIDAD DE INVENTARIO 
CREATE VIEW [dbo].[ARTICULOS EN STOCK] AS
SELECT
	id_item AS [item],
	nom_articulo AS [NOMBRE DE ARTICULO],
	unidades_disponibles AS [UNIDADES DISPONIBLES]
FROM INVENTARIO.ARTICULO
GO
/****** Object:  Table [PERSONA].[DIRECCION]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PERSONA].[DIRECCION](
	[id_direccion] [int] IDENTITY(1,1) NOT NULL,
	[tipo_direccion] [tinyint] NOT NULL,
	[id_persona] [int] NOT NULL,
	[dir_pais] [tinyint] NOT NULL,
	[dir_provincia] [int] NOT NULL,
	[dir_ciudad] [int] NOT NULL,
	[dir_distrito] [int] NOT NULL,
	[dir_linea_1] [nvarchar](100) NOT NULL,
	[dir_linea_2] [nvarchar](100) NULL,
	[dir_codigo_postal] [varchar](10) NOT NULL,
 CONSTRAINT [PK__DIRECCION_89f8c17c] PRIMARY KEY CLUSTERED 
(
	[id_direccion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[INFO DE CLIENTE 24]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- NOMBRES, APELLIDOS, TELEFONOS, EMAIL Y DIRECCIÓN DEL CLIENTE 24
CREATE VIEW [dbo].[INFO DE CLIENTE 24] AS
SELECT 
A.id_persona,
	A.nom_cliente AS [nombre cliente],
	B.dir_codigo_postal AS [cod postal],
	C.direccion_email AS [email],
	D.campo_1+D.campo_2+D.campo_3+D.ext AS [telefono]
FROM PERSONA.CLIENTE A
inner join PERSONA.DIRECCION B ON A.id_persona=B.id_persona
inner join PERSONA.EMAIL C ON A.id_persona=C.id_email
inner join PERSONA.TELEFONO D ON A.id_persona=D.id_persona
WHERE A.id_persona = 9
GO
/****** Object:  Table [PERSONA].[PERSONA_DE_INTERES]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PERSONA].[PERSONA_DE_INTERES](
	[id_persona] [int] NOT NULL,
	[id_directorio] [int] NOT NULL,
	[id_proyecto] [int] NOT NULL,
	[puesto] [smallint] NOT NULL,
	[nom_persona] [varchar](200) NOT NULL,
 CONSTRAINT [PK__PERSONA_DE_INTERES_8e557ca0] PRIMARY KEY CLUSTERED 
(
	[id_persona] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [PROYECTO].[DIRECTORIO]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PROYECTO].[DIRECTORIO](
	[id_directorio] [int] IDENTITY(1,1) NOT NULL,
	[id_proyecto] [int] NOT NULL,
 CONSTRAINT [PK__DIRECTORIO_da97306c] PRIMARY KEY CLUSTERED 
(
	[id_directorio] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[DIRECTORIO DE PROYECTO 653]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- MOSTRAR LAS PERSONAS DE INTERES DEL DIRECTORIO DEL PROYECTO 653
CREATE VIEW [dbo].[DIRECTORIO DE PROYECTO 653] AS 
SELECT 
	A.nom_persona AS [ID DE PROYECTO],
	B.id_directorio AS [ID DIRECTORIO ],
	B.id_proyecto
FROM PERSONA.PERSONA_DE_INTERES A
INNER JOIN PROYECTO.DIRECTORIO B ON A.id_directorio = B.id_directorio
WHERE B.id_proyecto = 653
GO
/****** Object:  View [dbo].[DETALLES DE ORDEN POR DESPACHO]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


-- TODOS LOS DETALLES DE LAS ORDENES POR CADA DESPACHO
CREATE VIEW [dbo].[DETALLES DE ORDEN POR DESPACHO] AS
SELECT 
		A.id_orden  AS [ID ORDEN],
		A.id_proyecto AS [ID PROYECTO],
		B.cantidad AS [CANTIDAD],
		B.precio_unitario [PRECIO UNITARIO],
		B.descuento_unitario_prcnt [DESCUENTO],
		B.precio_total_unidades [PRECIO TOTAL]
FROM VENTA.ORDEN A
INNER JOIN VENTA.DETALLE_DE_ORDEN B ON A.id_orden = B.id_orden
WHERE A.id_proyecto = 64
GO
/****** Object:  Table [PERSONA].[TELEFONOS_TIPOS]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PERSONA].[TELEFONOS_TIPOS](
	[tipo_telefono] [tinyint] IDENTITY(1,1) NOT NULL,
	[nombre_telefono] [varchar](50) NOT NULL,
 CONSTRAINT [PK__TIPO_TELEFONO_9701f915] PRIMARY KEY CLUSTERED 
(
	[tipo_telefono] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[TELEFONOS DIRECTORIO 16]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- MOSTRAR LOS NOMBRES DEL TELEFONO DE LAS PERSONAS EN EL DIRECTORIO 16
CREATE VIEW [dbo].[TELEFONOS DIRECTORIO 16] AS
SELECT
	A.nombre_telefono,
	B.tipo_telefono,
	E.id_directorio
FROM PERSONA.TELEFONOS_TIPOS A 
INNER JOIN PERSONA.TELEFONO B ON A.tipo_telefono = B.tipo_telefono 
INNER JOIN PERSONA.ID_PERSONA C ON B.id_persona = C.id_persona
INNER JOIN PERSONA.PERSONA_DE_INTERES D ON C.id_persona = D.id_persona
INNER JOIN PROYECTO.DIRECTORIO E ON D.id_directorio = E.id_directorio
WHERE D.id_directorio = 16
GO
/****** Object:  View [dbo].[PAISES DE CLIENTES]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


-- MOSTRAR EL PAIS DE LA PERSONA CLIENTE
CREATE VIEW [dbo].[PAISES DE CLIENTES] AS
SELECT 
	A.nom_pais AS [PAIS], C.nom_cliente AS[NOMBRE DEL CLIENTE]
FROM PERSONA.DIRECCION_PAIS A
INNER JOIN PERSONA.DIRECCION B ON A.id_pais = B.dir_pais
INNER JOIN PERSONA.CLIENTE C ON B.id_persona = C.id_persona
GO
/****** Object:  Table [DOCUMENTO].[DETALLE_COTIZACION]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [DOCUMENTO].[DETALLE_COTIZACION](
	[id_cotizacion] [int] NOT NULL,
	[id_detalle_cotizacion] [uniqueidentifier] NOT NULL,
	[id_item] [int] NOT NULL,
	[precio_unitario] [money] NOT NULL,
	[cantidad] [int] NOT NULL,
	[descuento] [decimal](18, 0) NOT NULL,
 CONSTRAINT [PK__DETALLE_COTIZACION_1s5f9w4a] PRIMARY KEY CLUSTERED 
(
	[id_cotizacion] ASC,
	[id_detalle_cotizacion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [DOCUMENTO].[DETALLE_LISTA_DE_MATERIALES]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [DOCUMENTO].[DETALLE_LISTA_DE_MATERIALES](
	[id_lista] [int] NOT NULL,
	[id_detalle_lista] [uniqueidentifier] NOT NULL,
	[id_item] [int] NOT NULL,
	[cantidad] [int] NOT NULL,
 CONSTRAINT [PK__DETALLE_LISTA_MATERIALES_5f1g4w9s] PRIMARY KEY CLUSTERED 
(
	[id_lista] ASC,
	[id_detalle_lista] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [DOCUMENTO].[ENTREGA_FINAL]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [DOCUMENTO].[ENTREGA_FINAL](
	[id_documento] [int] NOT NULL,
	[id_proyecto] [int] NOT NULL,
	[id_encargado] [int] NOT NULL,
	[path_scan_reporte] [varchar](256) NOT NULL,
	[fecha] [date] NULL,
 CONSTRAINT [PK__ENTREGA_FINAL_c99787ef] PRIMARY KEY CLUSTERED 
(
	[id_documento] ASC,
	[id_proyecto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [DOCUMENTO].[ID_DOCUMENTO]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [DOCUMENTO].[ID_DOCUMENTO](
	[id_documento] [int] IDENTITY(1,1) NOT NULL,
	[uid] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK__ID_DOCUMENTO_23b215c8] PRIMARY KEY CLUSTERED 
(
	[id_documento] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [DOCUMENTO].[LISTA_DE_MATERIALES]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [DOCUMENTO].[LISTA_DE_MATERIALES](
	[id_documento] [int] NOT NULL,
	[proyecto] [int] NOT NULL,
	[pedido_por] [int] NOT NULL,
	[fecha_pedida] [date] NULL,
	[fecha_aprobada] [date] NULL,
	[aprobado] [bit] NOT NULL,
	[aprobado_por] [int] NOT NULL,
	[ingresado_por] [int] NOT NULL,
 CONSTRAINT [PK__LISTA_MATERIALES_8fds9u2r] PRIMARY KEY CLUSTERED 
(
	[id_documento] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [DOCUMENTO].[PLANO]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [DOCUMENTO].[PLANO](
	[id_documento] [int] NOT NULL,
	[id_proyecto] [int] NOT NULL,
	[revision] [nchar](3) NOT NULL,
	[tipo_plano] [int] NOT NULL,
	[dibujado_por] [int] NOT NULL,
	[revisado_por] [int] NOT NULL,
	[nom_plano] [nvarchar](99) NOT NULL,
	[fecha_creacion] [date] NULL,
	[fecha_revision] [date] NULL,
	[fecha_envio] [date] NULL,
	[path_plano] [varchar](256) NOT NULL,
 CONSTRAINT [PK__PLANO_b19361e5] PRIMARY KEY CLUSTERED 
(
	[id_documento] ASC,
	[id_proyecto] ASC,
	[revision] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [DOCUMENTO].[PLANO_TIPO]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [DOCUMENTO].[PLANO_TIPO](
	[id_tipo_plano] [int] IDENTITY(1,1) NOT NULL,
	[nom_tipo_plano] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK__TIPO_PLANO_4e9b088a] PRIMARY KEY CLUSTERED 
(
	[id_tipo_plano] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [DOCUMENTO].[REPORTE_SUPERVISION]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [DOCUMENTO].[REPORTE_SUPERVISION](
	[id_documento] [int] NOT NULL,
	[id_proyecto] [int] NOT NULL,
	[id_supervisor] [int] NOT NULL,
	[fecha_reporte] [date] NULL,
	[detalles_reporte] [varchar](999) NULL,
	[path_scan_reporte] [varchar](256) NOT NULL,
 CONSTRAINT [PK__REPORTE_SUPERVISION_76f407d5] PRIMARY KEY CLUSTERED 
(
	[id_documento] ASC,
	[id_proyecto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [DOCUMENTO].[REPORTE_TECNICO]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [DOCUMENTO].[REPORTE_TECNICO](
	[id_documento] [int] NOT NULL,
	[id_proyecto] [int] NOT NULL,
	[id_tecnico] [int] NOT NULL,
	[fecha_reporte] [date] NULL,
	[detalles_reporte] [varchar](999) NULL,
	[path_scan_reporte] [varchar](256) NOT NULL,
 CONSTRAINT [PK__REPORTE_TECNICO_f8723e81] PRIMARY KEY CLUSTERED 
(
	[id_documento] ASC,
	[id_proyecto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [INVENTARIO].[ESPECIALIDADES_PROV]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [INVENTARIO].[ESPECIALIDADES_PROV](
	[id_especialidad] [int] IDENTITY(1,1) NOT NULL,
	[nom_especialidad] [varchar](99) NOT NULL,
	[desc_especialidad] [varchar](99) NULL,
 CONSTRAINT [PK__ESPECIALIDADES_PROV_6029e552] PRIMARY KEY CLUSTERED 
(
	[id_especialidad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [MARKETING].[CONTACTO_INICIAL]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MARKETING].[CONTACTO_INICIAL](
	[id_contacto] [smallint] IDENTITY(1,1) NOT NULL,
	[nom_forma_contacto] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK__CONTACTO_INICIAL_a58f0fbf] PRIMARY KEY CLUSTERED 
(
	[id_contacto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [MARKETING].[FICHA_MARKETING]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MARKETING].[FICHA_MARKETING](
	[id_ficha_marketing] [int] IDENTITY(1,1) NOT NULL,
	[id_persona_fuente] [int] NOT NULL,
	[forma_contacto_inical] [smallint] NOT NULL,
	[primer_interes] [smallint] NOT NULL,
	[fecha_primer_contacto] [datetime] NOT NULL,
	[fecha_ultimo_contacto] [datetime] NOT NULL,
 CONSTRAINT [PK__MARKETING_527ffe29] PRIMARY KEY CLUSTERED 
(
	[id_ficha_marketing] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [MARKETING].[PRIMER_INTERES]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MARKETING].[PRIMER_INTERES](
	[id_interes] [smallint] IDENTITY(1,1) NOT NULL,
	[desc_primer_interes] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK__PRIMER_INTERES_0f5a7ba3] PRIMARY KEY CLUSTERED 
(
	[id_interes] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [PERSONA].[CREDENTIAL]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PERSONA].[CREDENTIAL](
	[id_usuario] [int] IDENTITY(1,1) NOT NULL,
	[usuario] [nvarchar](16) NOT NULL,
	[password] [nvarchar](128) NOT NULL,
	[salt] [nvarchar](128) NOT NULL,
	[active] [bit] NOT NULL,
	[empleado] [int] NOT NULL,
 CONSTRAINT [PK_PERSONA_CREDENTIAL] PRIMARY KEY CLUSTERED 
(
	[id_usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [PERSONA].[DIRECCION_CIUDAD]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PERSONA].[DIRECCION_CIUDAD](
	[id_region] [int] NOT NULL,
	[id_ciudad] [int] IDENTITY(1,1) NOT NULL,
	[nom_ciudad] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK__CIUDAD_78a42696] PRIMARY KEY CLUSTERED 
(
	[id_ciudad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [PERSONA].[DIRECCION_DISTRITO]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PERSONA].[DIRECCION_DISTRITO](
	[id_ciudad] [int] NOT NULL,
	[id_distrito] [int] IDENTITY(1,1) NOT NULL,
	[nom_distrito] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK__DISTRITO_d1f78s6c] PRIMARY KEY CLUSTERED 
(
	[id_distrito] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [PERSONA].[DIRECCION_REGION]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PERSONA].[DIRECCION_REGION](
	[id_pais] [tinyint] NOT NULL,
	[id_region] [int] IDENTITY(1,1) NOT NULL,
	[nom_region] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK__REGION_89d3f635] PRIMARY KEY CLUSTERED 
(
	[id_region] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [PERSONA].[DIRECCION_TIPOS]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PERSONA].[DIRECCION_TIPOS](
	[tipo_direccion] [tinyint] IDENTITY(1,1) NOT NULL,
	[nombre_direccion] [varchar](50) NOT NULL,
 CONSTRAINT [PK__TIPO_DIRECCION_ffea2749] PRIMARY KEY CLUSTERED 
(
	[tipo_direccion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [PERSONA].[SALARIO_HISTORIAL]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PERSONA].[SALARIO_HISTORIAL](
	[id_persona] [int] NOT NULL,
	[id_salario] [int] NOT NULL,
	[monto] [money] NOT NULL,
	[frequencia_de_pago] [tinyint] NOT NULL,
	[fecha_modificada] [datetime] NOT NULL,
 CONSTRAINT [PK__SALARIO_HISTORIAL_4e9fd8ge] PRIMARY KEY CLUSTERED 
(
	[id_persona] ASC,
	[id_salario] ASC,
	[fecha_modificada] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [PROYECTO].[DIVISION]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PROYECTO].[DIVISION](
	[id_division] [tinyint] IDENTITY(1,1) NOT NULL,
	[nombre_division] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK__DIVISION_0cb9d11e] PRIMARY KEY CLUSTERED 
(
	[id_division] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [VENTA].[DESPACHO]    Script Date: 7/8/2020 8:40:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [VENTA].[DESPACHO](
	[id_despacho] [int] IDENTITY(1,1) NOT NULL,
	[id_venta] [int] NOT NULL,
	[aprobado_por] [int] NOT NULL,
	[fecha_de_creacion] [datetime] NOT NULL,
	[fecha_de_salida] [datetime] NOT NULL,
	[id_encargado] [int] NOT NULL,
	[placa_cargador] [varchar](16) NOT NULL,
	[direccion_de_envio] [int] NOT NULL,
 CONSTRAINT [PK__DESPACHO_3585f1ae] PRIMARY KEY CLUSTERED 
(
	[id_despacho] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO