//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARTICULO()
        {
            this.DETALLE_COTIZACION = new HashSet<DETALLE_COTIZACION>();
            this.DETALLE_LISTA_DE_MATERIALES = new HashSet<DETALLE_LISTA_DE_MATERIALES>();
            this.DETALLE_DE_ORDEN = new HashSet<DETALLE_DE_ORDEN>();
        }
    
        public int id_item { get; set; }
        public string nom_articulo { get; set; }
        public string marca_articulo { get; set; }
        public string descripcion_articulo { get; set; }
        public string unidad_medida_articulo { get; set; }
        public Nullable<decimal> valor_unitario { get; set; }
        public Nullable<int> unidades_disponibles { get; set; }
        public Nullable<int> id_proveedor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_COTIZACION> DETALLE_COTIZACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_LISTA_DE_MATERIALES> DETALLE_LISTA_DE_MATERIALES { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_DE_ORDEN> DETALLE_DE_ORDEN { get; set; }
    }
}
