//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class COTIZACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COTIZACION()
        {
            this.DETALLE_COTIZACION = new HashSet<DETALLE_COTIZACION>();
        }
    
        public int id_documento { get; set; }
        public int id_proyecto { get; set; }
        public int id_encargado { get; set; }
        public Nullable<int> id_aprobado_por { get; set; }
        public Nullable<int> enviar_a { get; set; }
        public Nullable<System.DateTime> fecha_aprobacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_envio { get; set; }
        public string notas { get; set; }
        public string path_archivo { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual EMPLEADO EMPLEADO1 { get; set; }
        public virtual ID_DOCUMENTO ID_DOCUMENTO1 { get; set; }
        public virtual PROYECTO PROYECTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_COTIZACION> DETALLE_COTIZACION { get; set; }
    }
}
