//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESPACHO
    {
        public int id_despacho { get; set; }
        public int id_venta { get; set; }
        public int aprobado_por { get; set; }
        public System.DateTime fecha_de_creacion { get; set; }
        public System.DateTime fecha_de_salida { get; set; }
        public int id_encargado { get; set; }
        public string placa_cargador { get; set; }
        public int direccion_de_envio { get; set; }
    
        public virtual DIRECCION DIRECCION { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual EMPLEADO EMPLEADO1 { get; set; }
        public virtual ORDEN ORDEN { get; set; }
    }
}
