//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_LISTA_DE_MATERIALES
    {
        public int id_lista { get; set; }
        public System.Guid id_detalle_lista { get; set; }
        public int id_item { get; set; }
        public int cantidad { get; set; }
    
        public virtual ARTICULO ARTICULO { get; set; }
    }
}
