//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_DE_ORDEN
    {
        public int id_orden { get; set; }
        public System.Guid id_detalle_orden { get; set; }
        public int id_item { get; set; }
        public int cantidad { get; set; }
        public decimal precio_unitario { get; set; }
        public decimal descuento_unitario_prcnt { get; set; }
        public decimal precio_total_unidades { get; set; }
    
        public virtual ARTICULO ARTICULO { get; set; }
        public virtual ORDEN ORDEN { get; set; }
    }
}
