//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIRECCION()
        {
            this.DESPACHOes = new HashSet<DESPACHO>();
        }
    
        public int id_direccion { get; set; }
        public byte tipo_direccion { get; set; }
        public int id_persona { get; set; }
        public byte dir_pais { get; set; }
        public int dir_provincia { get; set; }
        public int dir_ciudad { get; set; }
        public int dir_distrito { get; set; }
        public string dir_linea_1 { get; set; }
        public string dir_linea_2 { get; set; }
        public string dir_codigo_postal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DESPACHO> DESPACHOes { get; set; }
        public virtual DIRECCION_DISTRITO DIRECCION_DISTRITO { get; set; }
        public virtual ID_PERSONA ID_PERSONA1 { get; set; }
        public virtual DIRECCION_TIPOS DIRECCION_TIPOS { get; set; }
        public virtual DIRECCION_CIUDAD DIRECCION_CIUDAD { get; set; }
        public virtual DIRECCION_REGION DIRECCION_REGION { get; set; }
        public virtual DIRECCION_PAIS DIRECCION_PAIS { get; set; }
    }
}
