//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL
    {
        public int id_email { get; set; }
        public byte tipo_email { get; set; }
        public int id_persona { get; set; }
        public string direccion_email { get; set; }
    
        public virtual EMAIL_TIPOS EMAIL_TIPOS { get; set; }
        public virtual ID_PERSONA ID_PERSONA1 { get; set; }
    }
}
