//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADO()
        {
            this.COTIZACIONs = new HashSet<COTIZACION>();
            this.COTIZACIONs1 = new HashSet<COTIZACION>();
            this.ENTREGA_FINAL = new HashSet<ENTREGA_FINAL>();
            this.LISTA_DE_MATERIALES = new HashSet<LISTA_DE_MATERIALES>();
            this.LISTA_DE_MATERIALES1 = new HashSet<LISTA_DE_MATERIALES>();
            this.LISTA_DE_MATERIALES2 = new HashSet<LISTA_DE_MATERIALES>();
            this.PLANOes = new HashSet<PLANO>();
            this.PLANOes1 = new HashSet<PLANO>();
            this.REPORTE_SUPERVISION = new HashSet<REPORTE_SUPERVISION>();
            this.REPORTE_TECNICO = new HashSet<REPORTE_TECNICO>();
            this.ENVIOs = new HashSet<ENVIO>();
            this.FICHA_MARKETING = new HashSet<FICHA_MARKETING>();
            this.CREDENTIALs = new HashSet<CREDENTIAL>();
            this.DESPACHOes = new HashSet<DESPACHO>();
            this.DESPACHOes1 = new HashSet<DESPACHO>();
            this.ORDENs = new HashSet<ORDEN>();
            this.SALARIOs = new HashSet<SALARIO>();
        }
    
        public int id_persona { get; set; }
        public short puesto_empleado { get; set; }
        public string doc_oficial { get; set; }
        public string ruc_empleado { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public string primer_nom { get; set; }
        public string segundo_nom { get; set; }
        public string primer_ape { get; set; }
        public string segundo_ape { get; set; }
        public Nullable<bool> estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COTIZACION> COTIZACIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COTIZACION> COTIZACIONs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTREGA_FINAL> ENTREGA_FINAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LISTA_DE_MATERIALES> LISTA_DE_MATERIALES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LISTA_DE_MATERIALES> LISTA_DE_MATERIALES1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LISTA_DE_MATERIALES> LISTA_DE_MATERIALES2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANO> PLANOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANO> PLANOes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPORTE_SUPERVISION> REPORTE_SUPERVISION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPORTE_TECNICO> REPORTE_TECNICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENVIO> ENVIOs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FICHA_MARKETING> FICHA_MARKETING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CREDENTIAL> CREDENTIALs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DESPACHO> DESPACHOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DESPACHO> DESPACHOes1 { get; set; }
        public virtual PUESTO PUESTO { get; set; }
        public virtual ID_PERSONA ID_PERSONA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN> ORDENs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALARIO> SALARIOs { get; set; }
    }
}
