//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENVIO
    {
        public int id_envio { get; set; }
        public int id_recividor { get; set; }
        public int id_ficha_marketing { get; set; }
        public int id_enviador { get; set; }
        public short presentacion_enviada { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual ENVIABLE ENVIABLE { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual FICHA_MARKETING FICHA_MARKETING { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
    }
}
