//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class FICHA_MARKETING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FICHA_MARKETING()
        {
            this.ENVIOs = new HashSet<ENVIO>();
            this.CLIENTEs = new HashSet<CLIENTE>();
        }
    
        public int id_ficha_marketing { get; set; }
        public int id_persona_fuente { get; set; }
        public short forma_contacto_inical { get; set; }
        public short primer_interes { get; set; }
        public System.DateTime fecha_primer_contacto { get; set; }
        public System.DateTime fecha_ultimo_contacto { get; set; }
    
        public virtual CONTACTO_INICIAL CONTACTO_INICIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENVIO> ENVIOs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE> CLIENTEs { get; set; }
        public virtual PRIMER_INTERES PRIMER_INTERES1 { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
    }
}
