//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class grubalEntities : DbContext
    {
        public grubalEntities()
            : base("name=grubalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COTIZACION> COTIZACIONs { get; set; }
        public virtual DbSet<DETALLE_COTIZACION> DETALLE_COTIZACION { get; set; }
        public virtual DbSet<DETALLE_LISTA_DE_MATERIALES> DETALLE_LISTA_DE_MATERIALES { get; set; }
        public virtual DbSet<ENTREGA_FINAL> ENTREGA_FINAL { get; set; }
        public virtual DbSet<ID_DOCUMENTO> ID_DOCUMENTO { get; set; }
        public virtual DbSet<LISTA_DE_MATERIALES> LISTA_DE_MATERIALES { get; set; }
        public virtual DbSet<PLANO> PLANOes { get; set; }
        public virtual DbSet<PLANO_TIPO> PLANO_TIPO { get; set; }
        public virtual DbSet<REPORTE_SUPERVISION> REPORTE_SUPERVISION { get; set; }
        public virtual DbSet<REPORTE_TECNICO> REPORTE_TECNICO { get; set; }
        public virtual DbSet<ARTICULO> ARTICULOes { get; set; }
        public virtual DbSet<ESPECIALIDADES_PROV> ESPECIALIDADES_PROV { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDORs { get; set; }
        public virtual DbSet<CONTACTO_INICIAL> CONTACTO_INICIAL { get; set; }
        public virtual DbSet<ENVIABLE> ENVIABLEs { get; set; }
        public virtual DbSet<ENVIO> ENVIOs { get; set; }
        public virtual DbSet<FICHA_MARKETING> FICHA_MARKETING { get; set; }
        public virtual DbSet<PRIMER_INTERES> PRIMER_INTERES { get; set; }
        public virtual DbSet<CLIENTE> CLIENTEs { get; set; }
        public virtual DbSet<CREDENTIAL> CREDENTIALs { get; set; }
        public virtual DbSet<DIRECCION> DIRECCIONs { get; set; }
        public virtual DbSet<DIRECCION_CIUDAD> DIRECCION_CIUDAD { get; set; }
        public virtual DbSet<DIRECCION_DISTRITO> DIRECCION_DISTRITO { get; set; }
        public virtual DbSet<DIRECCION_PAIS> DIRECCION_PAIS { get; set; }
        public virtual DbSet<DIRECCION_REGION> DIRECCION_REGION { get; set; }
        public virtual DbSet<DIRECCION_TIPOS> DIRECCION_TIPOS { get; set; }
        public virtual DbSet<EMAIL> EMAILs { get; set; }
        public virtual DbSet<EMAIL_TIPOS> EMAIL_TIPOS { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADOes { get; set; }
        public virtual DbSet<ID_PERSONA> ID_PERSONA { get; set; }
        public virtual DbSet<PERSONA_DE_INTERES> PERSONA_DE_INTERES { get; set; }
        public virtual DbSet<PUESTO> PUESTOes { get; set; }
        public virtual DbSet<SALARIO> SALARIOs { get; set; }
        public virtual DbSet<SALARIO_HISTORIAL> SALARIO_HISTORIAL { get; set; }
        public virtual DbSet<TELEFONO> TELEFONOes { get; set; }
        public virtual DbSet<TELEFONOS_TIPOS> TELEFONOS_TIPOS { get; set; }
        public virtual DbSet<DIRECTORIO> DIRECTORIOs { get; set; }
        public virtual DbSet<DIVISION> DIVISIONs { get; set; }
        public virtual DbSet<PROYECTO> PROYECTOes { get; set; }
        public virtual DbSet<DESPACHO> DESPACHOes { get; set; }
        public virtual DbSet<DETALLE_DE_ORDEN> DETALLE_DE_ORDEN { get; set; }
        public virtual DbSet<ORDEN> ORDENs { get; set; }
    
        public virtual int ActualizarEntregaFinal(Nullable<int> id_documento, Nullable<int> id_proyecto, Nullable<int> id_encargado, string path_scan_reporte, Nullable<System.DateTime> fecha)
        {
            var id_documentoParameter = id_documento.HasValue ?
                new ObjectParameter("id_documento", id_documento) :
                new ObjectParameter("id_documento", typeof(int));
    
            var id_proyectoParameter = id_proyecto.HasValue ?
                new ObjectParameter("id_proyecto", id_proyecto) :
                new ObjectParameter("id_proyecto", typeof(int));
    
            var id_encargadoParameter = id_encargado.HasValue ?
                new ObjectParameter("id_encargado", id_encargado) :
                new ObjectParameter("id_encargado", typeof(int));
    
            var path_scan_reporteParameter = path_scan_reporte != null ?
                new ObjectParameter("path_scan_reporte", path_scan_reporte) :
                new ObjectParameter("path_scan_reporte", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarEntregaFinal", id_documentoParameter, id_proyectoParameter, id_encargadoParameter, path_scan_reporteParameter, fechaParameter);
        }
    
        public virtual int ActualizarReporteTecnico(Nullable<int> id_documento, Nullable<int> id_proyecto, Nullable<int> id_tecnico, Nullable<System.DateTime> fecha_reporte, string detalles_reporte, string path_scan_reporte)
        {
            var id_documentoParameter = id_documento.HasValue ?
                new ObjectParameter("id_documento", id_documento) :
                new ObjectParameter("id_documento", typeof(int));
    
            var id_proyectoParameter = id_proyecto.HasValue ?
                new ObjectParameter("id_proyecto", id_proyecto) :
                new ObjectParameter("id_proyecto", typeof(int));
    
            var id_tecnicoParameter = id_tecnico.HasValue ?
                new ObjectParameter("id_tecnico", id_tecnico) :
                new ObjectParameter("id_tecnico", typeof(int));
    
            var fecha_reporteParameter = fecha_reporte.HasValue ?
                new ObjectParameter("fecha_reporte", fecha_reporte) :
                new ObjectParameter("fecha_reporte", typeof(System.DateTime));
    
            var detalles_reporteParameter = detalles_reporte != null ?
                new ObjectParameter("detalles_reporte", detalles_reporte) :
                new ObjectParameter("detalles_reporte", typeof(string));
    
            var path_scan_reporteParameter = path_scan_reporte != null ?
                new ObjectParameter("path_scan_reporte", path_scan_reporte) :
                new ObjectParameter("path_scan_reporte", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarReporteTecnico", id_documentoParameter, id_proyectoParameter, id_tecnicoParameter, fecha_reporteParameter, detalles_reporteParameter, path_scan_reporteParameter);
        }
    
        public virtual int CotizacionNew(Nullable<int> id_proyecto, Nullable<int> id_encargado, Nullable<int> id_aprobado_por, Nullable<int> enviar_a, Nullable<System.DateTime> fecha_aprobacion, Nullable<System.DateTime> fecha_creacion, Nullable<System.DateTime> fecha_envio, string notas, string path_archivo, ObjectParameter rnid)
        {
            var id_proyectoParameter = id_proyecto.HasValue ?
                new ObjectParameter("id_proyecto", id_proyecto) :
                new ObjectParameter("id_proyecto", typeof(int));
    
            var id_encargadoParameter = id_encargado.HasValue ?
                new ObjectParameter("id_encargado", id_encargado) :
                new ObjectParameter("id_encargado", typeof(int));
    
            var id_aprobado_porParameter = id_aprobado_por.HasValue ?
                new ObjectParameter("id_aprobado_por", id_aprobado_por) :
                new ObjectParameter("id_aprobado_por", typeof(int));
    
            var enviar_aParameter = enviar_a.HasValue ?
                new ObjectParameter("enviar_a", enviar_a) :
                new ObjectParameter("enviar_a", typeof(int));
    
            var fecha_aprobacionParameter = fecha_aprobacion.HasValue ?
                new ObjectParameter("fecha_aprobacion", fecha_aprobacion) :
                new ObjectParameter("fecha_aprobacion", typeof(System.DateTime));
    
            var fecha_creacionParameter = fecha_creacion.HasValue ?
                new ObjectParameter("fecha_creacion", fecha_creacion) :
                new ObjectParameter("fecha_creacion", typeof(System.DateTime));
    
            var fecha_envioParameter = fecha_envio.HasValue ?
                new ObjectParameter("fecha_envio", fecha_envio) :
                new ObjectParameter("fecha_envio", typeof(System.DateTime));
    
            var notasParameter = notas != null ?
                new ObjectParameter("notas", notas) :
                new ObjectParameter("notas", typeof(string));
    
            var path_archivoParameter = path_archivo != null ?
                new ObjectParameter("path_archivo", path_archivo) :
                new ObjectParameter("path_archivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CotizacionNew", id_proyectoParameter, id_encargadoParameter, id_aprobado_porParameter, enviar_aParameter, fecha_aprobacionParameter, fecha_creacionParameter, fecha_envioParameter, notasParameter, path_archivoParameter, rnid);
        }
    
        public virtual ObjectResult<crud_LISTA_DE_MATERIALESSelect_Result> crud_LISTA_DE_MATERIALESSelect(Nullable<int> proyecto)
        {
            var proyectoParameter = proyecto.HasValue ?
                new ObjectParameter("proyecto", proyecto) :
                new ObjectParameter("proyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<crud_LISTA_DE_MATERIALESSelect_Result>("crud_LISTA_DE_MATERIALESSelect", proyectoParameter);
        }
    
        public virtual int EliminarEntregaFinal(Nullable<int> id_documento)
        {
            var id_documentoParameter = id_documento.HasValue ?
                new ObjectParameter("id_documento", id_documento) :
                new ObjectParameter("id_documento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarEntregaFinal", id_documentoParameter);
        }
    
        public virtual int EliminarPlano(Nullable<int> id_documento)
        {
            var id_documentoParameter = id_documento.HasValue ?
                new ObjectParameter("id_documento", id_documento) :
                new ObjectParameter("id_documento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarPlano", id_documentoParameter);
        }
    
        public virtual int EliminarReporteSupervision(Nullable<int> id_documento)
        {
            var id_documentoParameter = id_documento.HasValue ?
                new ObjectParameter("id_documento", id_documento) :
                new ObjectParameter("id_documento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarReporteSupervision", id_documentoParameter);
        }
    
        public virtual int EliminarReporteTecnico(Nullable<int> id_documento)
        {
            var id_documentoParameter = id_documento.HasValue ?
                new ObjectParameter("id_documento", id_documento) :
                new ObjectParameter("id_documento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarReporteTecnico", id_documentoParameter);
        }
    
        public virtual int EntregaFinalNew(Nullable<int> id_proyecto, Nullable<int> id_encargado, string path_scan_reporte, Nullable<System.DateTime> fecha)
        {
            var id_proyectoParameter = id_proyecto.HasValue ?
                new ObjectParameter("id_proyecto", id_proyecto) :
                new ObjectParameter("id_proyecto", typeof(int));
    
            var id_encargadoParameter = id_encargado.HasValue ?
                new ObjectParameter("id_encargado", id_encargado) :
                new ObjectParameter("id_encargado", typeof(int));
    
            var path_scan_reporteParameter = path_scan_reporte != null ?
                new ObjectParameter("path_scan_reporte", path_scan_reporte) :
                new ObjectParameter("path_scan_reporte", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EntregaFinalNew", id_proyectoParameter, id_encargadoParameter, path_scan_reporteParameter, fechaParameter);
        }
    
        public virtual int InsertarPlano(Nullable<int> id_proyecto, string revision, Nullable<int> tipo_plano, Nullable<int> dibujado_por, Nullable<int> revisado_por, string nom_plano, Nullable<System.DateTime> fecha_creacion, Nullable<System.DateTime> fecha_revision, Nullable<System.DateTime> fecha_envio, string path_plano)
        {
            var id_proyectoParameter = id_proyecto.HasValue ?
                new ObjectParameter("id_proyecto", id_proyecto) :
                new ObjectParameter("id_proyecto", typeof(int));
    
            var revisionParameter = revision != null ?
                new ObjectParameter("revision", revision) :
                new ObjectParameter("revision", typeof(string));
    
            var tipo_planoParameter = tipo_plano.HasValue ?
                new ObjectParameter("tipo_plano", tipo_plano) :
                new ObjectParameter("tipo_plano", typeof(int));
    
            var dibujado_porParameter = dibujado_por.HasValue ?
                new ObjectParameter("dibujado_por", dibujado_por) :
                new ObjectParameter("dibujado_por", typeof(int));
    
            var revisado_porParameter = revisado_por.HasValue ?
                new ObjectParameter("revisado_por", revisado_por) :
                new ObjectParameter("revisado_por", typeof(int));
    
            var nom_planoParameter = nom_plano != null ?
                new ObjectParameter("nom_plano", nom_plano) :
                new ObjectParameter("nom_plano", typeof(string));
    
            var fecha_creacionParameter = fecha_creacion.HasValue ?
                new ObjectParameter("fecha_creacion", fecha_creacion) :
                new ObjectParameter("fecha_creacion", typeof(System.DateTime));
    
            var fecha_revisionParameter = fecha_revision.HasValue ?
                new ObjectParameter("fecha_revision", fecha_revision) :
                new ObjectParameter("fecha_revision", typeof(System.DateTime));
    
            var fecha_envioParameter = fecha_envio.HasValue ?
                new ObjectParameter("fecha_envio", fecha_envio) :
                new ObjectParameter("fecha_envio", typeof(System.DateTime));
    
            var path_planoParameter = path_plano != null ?
                new ObjectParameter("path_plano", path_plano) :
                new ObjectParameter("path_plano", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertarPlano", id_proyectoParameter, revisionParameter, tipo_planoParameter, dibujado_porParameter, revisado_porParameter, nom_planoParameter, fecha_creacionParameter, fecha_revisionParameter, fecha_envioParameter, path_planoParameter);
        }
    
        public virtual int ListaMaterialesNew(Nullable<int> proyecto, Nullable<int> pedido_por, Nullable<System.DateTime> fecha_pedida, Nullable<System.DateTime> fecha_aprobada, Nullable<bool> aprobado, Nullable<int> aprobado_por, Nullable<int> ingresado_por, ObjectParameter rnid)
        {
            var proyectoParameter = proyecto.HasValue ?
                new ObjectParameter("proyecto", proyecto) :
                new ObjectParameter("proyecto", typeof(int));
    
            var pedido_porParameter = pedido_por.HasValue ?
                new ObjectParameter("pedido_por", pedido_por) :
                new ObjectParameter("pedido_por", typeof(int));
    
            var fecha_pedidaParameter = fecha_pedida.HasValue ?
                new ObjectParameter("fecha_pedida", fecha_pedida) :
                new ObjectParameter("fecha_pedida", typeof(System.DateTime));
    
            var fecha_aprobadaParameter = fecha_aprobada.HasValue ?
                new ObjectParameter("fecha_aprobada", fecha_aprobada) :
                new ObjectParameter("fecha_aprobada", typeof(System.DateTime));
    
            var aprobadoParameter = aprobado.HasValue ?
                new ObjectParameter("aprobado", aprobado) :
                new ObjectParameter("aprobado", typeof(bool));
    
            var aprobado_porParameter = aprobado_por.HasValue ?
                new ObjectParameter("aprobado_por", aprobado_por) :
                new ObjectParameter("aprobado_por", typeof(int));
    
            var ingresado_porParameter = ingresado_por.HasValue ?
                new ObjectParameter("ingresado_por", ingresado_por) :
                new ObjectParameter("ingresado_por", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaMaterialesNew", proyectoParameter, pedido_porParameter, fecha_pedidaParameter, fecha_aprobadaParameter, aprobadoParameter, aprobado_porParameter, ingresado_porParameter, rnid);
        }
    
        public virtual ObjectResult<ListarCotizacionesPorProyecto_Result> ListarCotizacionesPorProyecto(Nullable<int> id_proyecto)
        {
            var id_proyectoParameter = id_proyecto.HasValue ?
                new ObjectParameter("id_proyecto", id_proyecto) :
                new ObjectParameter("id_proyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarCotizacionesPorProyecto_Result>("ListarCotizacionesPorProyecto", id_proyectoParameter);
        }
    
        public virtual ObjectResult<ListarEntregaFinalFull_Result> ListarEntregaFinalFull()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarEntregaFinalFull_Result>("ListarEntregaFinalFull");
        }
    
        public virtual ObjectResult<ListarEntregaFinalPorId_Result> ListarEntregaFinalPorId(Nullable<int> id_documento)
        {
            var id_documentoParameter = id_documento.HasValue ?
                new ObjectParameter("id_documento", id_documento) :
                new ObjectParameter("id_documento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarEntregaFinalPorId_Result>("ListarEntregaFinalPorId", id_documentoParameter);
        }
    
        public virtual ObjectResult<ListarEntregasFinalesPorFecha_Result> ListarEntregasFinalesPorFecha(Nullable<System.DateTime> fecha_inicio, Nullable<System.DateTime> fecha_fin)
        {
            var fecha_inicioParameter = fecha_inicio.HasValue ?
                new ObjectParameter("fecha_inicio", fecha_inicio) :
                new ObjectParameter("fecha_inicio", typeof(System.DateTime));
    
            var fecha_finParameter = fecha_fin.HasValue ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarEntregasFinalesPorFecha_Result>("ListarEntregasFinalesPorFecha", fecha_inicioParameter, fecha_finParameter);
        }
    
        public virtual ObjectResult<ListarMaterialesPorProyecto_Result> ListarMaterialesPorProyecto(Nullable<int> proyecto)
        {
            var proyectoParameter = proyecto.HasValue ?
                new ObjectParameter("proyecto", proyecto) :
                new ObjectParameter("proyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarMaterialesPorProyecto_Result>("ListarMaterialesPorProyecto", proyectoParameter);
        }
    
        public virtual ObjectResult<ListarPlanosFull_Result> ListarPlanosFull()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarPlanosFull_Result>("ListarPlanosFull");
        }
    
        public virtual ObjectResult<ListarPlanosPorId_Result> ListarPlanosPorId(Nullable<int> id_documento)
        {
            var id_documentoParameter = id_documento.HasValue ?
                new ObjectParameter("id_documento", id_documento) :
                new ObjectParameter("id_documento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarPlanosPorId_Result>("ListarPlanosPorId", id_documentoParameter);
        }
    
        public virtual ObjectResult<ListarPlanosPorProyecto_Result> ListarPlanosPorProyecto(Nullable<int> id_proyecto)
        {
            var id_proyectoParameter = id_proyecto.HasValue ?
                new ObjectParameter("id_proyecto", id_proyecto) :
                new ObjectParameter("id_proyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarPlanosPorProyecto_Result>("ListarPlanosPorProyecto", id_proyectoParameter);
        }
    
        public virtual ObjectResult<ListarPlanosPorProyectoTipo_Result> ListarPlanosPorProyectoTipo(Nullable<int> id_proyecto, Nullable<int> id_tipo)
        {
            var id_proyectoParameter = id_proyecto.HasValue ?
                new ObjectParameter("id_proyecto", id_proyecto) :
                new ObjectParameter("id_proyecto", typeof(int));
    
            var id_tipoParameter = id_tipo.HasValue ?
                new ObjectParameter("id_tipo", id_tipo) :
                new ObjectParameter("id_tipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarPlanosPorProyectoTipo_Result>("ListarPlanosPorProyectoTipo", id_proyectoParameter, id_tipoParameter);
        }
    
        public virtual ObjectResult<ListarReporteSupervisionFull_Result> ListarReporteSupervisionFull()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarReporteSupervisionFull_Result>("ListarReporteSupervisionFull");
        }
    
        public virtual ObjectResult<ListarReporteSupervisionPorId_Result> ListarReporteSupervisionPorId(Nullable<int> id_documento)
        {
            var id_documentoParameter = id_documento.HasValue ?
                new ObjectParameter("id_documento", id_documento) :
                new ObjectParameter("id_documento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarReporteSupervisionPorId_Result>("ListarReporteSupervisionPorId", id_documentoParameter);
        }
    
        public virtual ObjectResult<ListarReporteSupervisionPorProyecto_Result> ListarReporteSupervisionPorProyecto(Nullable<int> id_proyecto)
        {
            var id_proyectoParameter = id_proyecto.HasValue ?
                new ObjectParameter("id_proyecto", id_proyecto) :
                new ObjectParameter("id_proyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarReporteSupervisionPorProyecto_Result>("ListarReporteSupervisionPorProyecto", id_proyectoParameter);
        }
    
        public virtual ObjectResult<ListarReporteSupervisionPorProyectoEmpleado_Result> ListarReporteSupervisionPorProyectoEmpleado(Nullable<int> id_proyecto, Nullable<int> id_supervisor)
        {
            var id_proyectoParameter = id_proyecto.HasValue ?
                new ObjectParameter("id_proyecto", id_proyecto) :
                new ObjectParameter("id_proyecto", typeof(int));
    
            var id_supervisorParameter = id_supervisor.HasValue ?
                new ObjectParameter("id_supervisor", id_supervisor) :
                new ObjectParameter("id_supervisor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarReporteSupervisionPorProyectoEmpleado_Result>("ListarReporteSupervisionPorProyectoEmpleado", id_proyectoParameter, id_supervisorParameter);
        }
    
        public virtual ObjectResult<ListarReporteTecnicoFull_Result> ListarReporteTecnicoFull()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarReporteTecnicoFull_Result>("ListarReporteTecnicoFull");
        }
    
        public virtual ObjectResult<ListarReporteTecnicoPorId_Result> ListarReporteTecnicoPorId(Nullable<int> id_documento)
        {
            var id_documentoParameter = id_documento.HasValue ?
                new ObjectParameter("id_documento", id_documento) :
                new ObjectParameter("id_documento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarReporteTecnicoPorId_Result>("ListarReporteTecnicoPorId", id_documentoParameter);
        }
    
        public virtual ObjectResult<ListarReporteTecnicoPorProyecto_Result> ListarReporteTecnicoPorProyecto(Nullable<int> id_proyecto)
        {
            var id_proyectoParameter = id_proyecto.HasValue ?
                new ObjectParameter("id_proyecto", id_proyecto) :
                new ObjectParameter("id_proyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarReporteTecnicoPorProyecto_Result>("ListarReporteTecnicoPorProyecto", id_proyectoParameter);
        }
    
        public virtual ObjectResult<ListarReporteTecnicoPorProyectoEmpleado_Result> ListarReporteTecnicoPorProyectoEmpleado(Nullable<int> id_proyecto, Nullable<int> id_tecnico)
        {
            var id_proyectoParameter = id_proyecto.HasValue ?
                new ObjectParameter("id_proyecto", id_proyecto) :
                new ObjectParameter("id_proyecto", typeof(int));
    
            var id_tecnicoParameter = id_tecnico.HasValue ?
                new ObjectParameter("id_tecnico", id_tecnico) :
                new ObjectParameter("id_tecnico", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarReporteTecnicoPorProyectoEmpleado_Result>("ListarReporteTecnicoPorProyectoEmpleado", id_proyectoParameter, id_tecnicoParameter);
        }
    
        public virtual ObjectResult<ListarTiposPlano_Result> ListarTiposPlano()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarTiposPlano_Result>("ListarTiposPlano");
        }
    
        public virtual int ModificarPlano(Nullable<int> id_documento, Nullable<int> id_proyecto, string revision, Nullable<int> tipo_plano, Nullable<int> dibujado_por, Nullable<int> revisado_por, string nom_plano, Nullable<System.DateTime> fecha_creacion, Nullable<System.DateTime> fecha_revision, Nullable<System.DateTime> fecha_envio, string path_plano)
        {
            var id_documentoParameter = id_documento.HasValue ?
                new ObjectParameter("id_documento", id_documento) :
                new ObjectParameter("id_documento", typeof(int));
    
            var id_proyectoParameter = id_proyecto.HasValue ?
                new ObjectParameter("id_proyecto", id_proyecto) :
                new ObjectParameter("id_proyecto", typeof(int));
    
            var revisionParameter = revision != null ?
                new ObjectParameter("revision", revision) :
                new ObjectParameter("revision", typeof(string));
    
            var tipo_planoParameter = tipo_plano.HasValue ?
                new ObjectParameter("tipo_plano", tipo_plano) :
                new ObjectParameter("tipo_plano", typeof(int));
    
            var dibujado_porParameter = dibujado_por.HasValue ?
                new ObjectParameter("dibujado_por", dibujado_por) :
                new ObjectParameter("dibujado_por", typeof(int));
    
            var revisado_porParameter = revisado_por.HasValue ?
                new ObjectParameter("revisado_por", revisado_por) :
                new ObjectParameter("revisado_por", typeof(int));
    
            var nom_planoParameter = nom_plano != null ?
                new ObjectParameter("nom_plano", nom_plano) :
                new ObjectParameter("nom_plano", typeof(string));
    
            var fecha_creacionParameter = fecha_creacion.HasValue ?
                new ObjectParameter("fecha_creacion", fecha_creacion) :
                new ObjectParameter("fecha_creacion", typeof(System.DateTime));
    
            var fecha_revisionParameter = fecha_revision.HasValue ?
                new ObjectParameter("fecha_revision", fecha_revision) :
                new ObjectParameter("fecha_revision", typeof(System.DateTime));
    
            var fecha_envioParameter = fecha_envio.HasValue ?
                new ObjectParameter("fecha_envio", fecha_envio) :
                new ObjectParameter("fecha_envio", typeof(System.DateTime));
    
            var path_planoParameter = path_plano != null ?
                new ObjectParameter("path_plano", path_plano) :
                new ObjectParameter("path_plano", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificarPlano", id_documentoParameter, id_proyectoParameter, revisionParameter, tipo_planoParameter, dibujado_porParameter, revisado_porParameter, nom_planoParameter, fecha_creacionParameter, fecha_revisionParameter, fecha_envioParameter, path_planoParameter);
        }
    
        public virtual int ModificarReporteSupervision(Nullable<int> id_documento, Nullable<int> id_proyecto, Nullable<int> id_supervisor, Nullable<System.DateTime> fecha_reporte, string detalles_reporte, string path_scan_reporte)
        {
            var id_documentoParameter = id_documento.HasValue ?
                new ObjectParameter("id_documento", id_documento) :
                new ObjectParameter("id_documento", typeof(int));
    
            var id_proyectoParameter = id_proyecto.HasValue ?
                new ObjectParameter("id_proyecto", id_proyecto) :
                new ObjectParameter("id_proyecto", typeof(int));
    
            var id_supervisorParameter = id_supervisor.HasValue ?
                new ObjectParameter("id_supervisor", id_supervisor) :
                new ObjectParameter("id_supervisor", typeof(int));
    
            var fecha_reporteParameter = fecha_reporte.HasValue ?
                new ObjectParameter("fecha_reporte", fecha_reporte) :
                new ObjectParameter("fecha_reporte", typeof(System.DateTime));
    
            var detalles_reporteParameter = detalles_reporte != null ?
                new ObjectParameter("detalles_reporte", detalles_reporte) :
                new ObjectParameter("detalles_reporte", typeof(string));
    
            var path_scan_reporteParameter = path_scan_reporte != null ?
                new ObjectParameter("path_scan_reporte", path_scan_reporte) :
                new ObjectParameter("path_scan_reporte", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificarReporteSupervision", id_documentoParameter, id_proyectoParameter, id_supervisorParameter, fecha_reporteParameter, detalles_reporteParameter, path_scan_reporteParameter);
        }
    
        public virtual int NewDocument(ObjectParameter newId)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NewDocument", newId);
        }
    
        public virtual int NuevoPlano(Nullable<int> id_proyecto, string revision, Nullable<int> tipo_plano, Nullable<int> dibujado_por, Nullable<int> revisado_por, string nom_plano, Nullable<System.DateTime> fecha_creacaion, Nullable<System.DateTime> fecha_revision, Nullable<System.DateTime> fecha_envio, string path_plano)
        {
            var id_proyectoParameter = id_proyecto.HasValue ?
                new ObjectParameter("id_proyecto", id_proyecto) :
                new ObjectParameter("id_proyecto", typeof(int));
    
            var revisionParameter = revision != null ?
                new ObjectParameter("revision", revision) :
                new ObjectParameter("revision", typeof(string));
    
            var tipo_planoParameter = tipo_plano.HasValue ?
                new ObjectParameter("tipo_plano", tipo_plano) :
                new ObjectParameter("tipo_plano", typeof(int));
    
            var dibujado_porParameter = dibujado_por.HasValue ?
                new ObjectParameter("dibujado_por", dibujado_por) :
                new ObjectParameter("dibujado_por", typeof(int));
    
            var revisado_porParameter = revisado_por.HasValue ?
                new ObjectParameter("revisado_por", revisado_por) :
                new ObjectParameter("revisado_por", typeof(int));
    
            var nom_planoParameter = nom_plano != null ?
                new ObjectParameter("nom_plano", nom_plano) :
                new ObjectParameter("nom_plano", typeof(string));
    
            var fecha_creacaionParameter = fecha_creacaion.HasValue ?
                new ObjectParameter("fecha_creacaion", fecha_creacaion) :
                new ObjectParameter("fecha_creacaion", typeof(System.DateTime));
    
            var fecha_revisionParameter = fecha_revision.HasValue ?
                new ObjectParameter("fecha_revision", fecha_revision) :
                new ObjectParameter("fecha_revision", typeof(System.DateTime));
    
            var fecha_envioParameter = fecha_envio.HasValue ?
                new ObjectParameter("fecha_envio", fecha_envio) :
                new ObjectParameter("fecha_envio", typeof(System.DateTime));
    
            var path_planoParameter = path_plano != null ?
                new ObjectParameter("path_plano", path_plano) :
                new ObjectParameter("path_plano", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NuevoPlano", id_proyectoParameter, revisionParameter, tipo_planoParameter, dibujado_porParameter, revisado_porParameter, nom_planoParameter, fecha_creacaionParameter, fecha_revisionParameter, fecha_envioParameter, path_planoParameter);
        }
    
        public virtual int ReporteSupervisionNew(Nullable<int> id_proyecto, Nullable<int> id_supervisor, Nullable<System.DateTime> fecha_reporte, string detalles_reporte, string path_scan_reporte)
        {
            var id_proyectoParameter = id_proyecto.HasValue ?
                new ObjectParameter("id_proyecto", id_proyecto) :
                new ObjectParameter("id_proyecto", typeof(int));
    
            var id_supervisorParameter = id_supervisor.HasValue ?
                new ObjectParameter("id_supervisor", id_supervisor) :
                new ObjectParameter("id_supervisor", typeof(int));
    
            var fecha_reporteParameter = fecha_reporte.HasValue ?
                new ObjectParameter("fecha_reporte", fecha_reporte) :
                new ObjectParameter("fecha_reporte", typeof(System.DateTime));
    
            var detalles_reporteParameter = detalles_reporte != null ?
                new ObjectParameter("detalles_reporte", detalles_reporte) :
                new ObjectParameter("detalles_reporte", typeof(string));
    
            var path_scan_reporteParameter = path_scan_reporte != null ?
                new ObjectParameter("path_scan_reporte", path_scan_reporte) :
                new ObjectParameter("path_scan_reporte", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ReporteSupervisionNew", id_proyectoParameter, id_supervisorParameter, fecha_reporteParameter, detalles_reporteParameter, path_scan_reporteParameter);
        }
    
        public virtual int ReporteTecnicoNew(Nullable<int> id_proyecto, Nullable<int> id_tecnico, Nullable<System.DateTime> fecha_reporte, string detalles_reporte, string path_scan_reporte)
        {
            var id_proyectoParameter = id_proyecto.HasValue ?
                new ObjectParameter("id_proyecto", id_proyecto) :
                new ObjectParameter("id_proyecto", typeof(int));
    
            var id_tecnicoParameter = id_tecnico.HasValue ?
                new ObjectParameter("id_tecnico", id_tecnico) :
                new ObjectParameter("id_tecnico", typeof(int));
    
            var fecha_reporteParameter = fecha_reporte.HasValue ?
                new ObjectParameter("fecha_reporte", fecha_reporte) :
                new ObjectParameter("fecha_reporte", typeof(System.DateTime));
    
            var detalles_reporteParameter = detalles_reporte != null ?
                new ObjectParameter("detalles_reporte", detalles_reporte) :
                new ObjectParameter("detalles_reporte", typeof(string));
    
            var path_scan_reporteParameter = path_scan_reporte != null ?
                new ObjectParameter("path_scan_reporte", path_scan_reporte) :
                new ObjectParameter("path_scan_reporte", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ReporteTecnicoNew", id_proyectoParameter, id_tecnicoParameter, fecha_reporteParameter, detalles_reporteParameter, path_scan_reporteParameter);
        }
    
        public virtual ObjectResult<ListarArticulos_Result> ListarArticulos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarArticulos_Result>("ListarArticulos");
        }
    
        public virtual int FichaMarketingActualizar(Nullable<int> id_ficha_marketing, Nullable<int> id_persona_fuente, Nullable<short> forma_contacto_inical, Nullable<short> primer_interes, Nullable<System.DateTime> fecha_primer_contacto, Nullable<System.DateTime> fecha_ultimo_contacto)
        {
            var id_ficha_marketingParameter = id_ficha_marketing.HasValue ?
                new ObjectParameter("id_ficha_marketing", id_ficha_marketing) :
                new ObjectParameter("id_ficha_marketing", typeof(int));
    
            var id_persona_fuenteParameter = id_persona_fuente.HasValue ?
                new ObjectParameter("id_persona_fuente", id_persona_fuente) :
                new ObjectParameter("id_persona_fuente", typeof(int));
    
            var forma_contacto_inicalParameter = forma_contacto_inical.HasValue ?
                new ObjectParameter("forma_contacto_inical", forma_contacto_inical) :
                new ObjectParameter("forma_contacto_inical", typeof(short));
    
            var primer_interesParameter = primer_interes.HasValue ?
                new ObjectParameter("primer_interes", primer_interes) :
                new ObjectParameter("primer_interes", typeof(short));
    
            var fecha_primer_contactoParameter = fecha_primer_contacto.HasValue ?
                new ObjectParameter("fecha_primer_contacto", fecha_primer_contacto) :
                new ObjectParameter("fecha_primer_contacto", typeof(System.DateTime));
    
            var fecha_ultimo_contactoParameter = fecha_ultimo_contacto.HasValue ?
                new ObjectParameter("fecha_ultimo_contacto", fecha_ultimo_contacto) :
                new ObjectParameter("fecha_ultimo_contacto", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FichaMarketingActualizar", id_ficha_marketingParameter, id_persona_fuenteParameter, forma_contacto_inicalParameter, primer_interesParameter, fecha_primer_contactoParameter, fecha_ultimo_contactoParameter);
        }
    
        public virtual int FichaMarketingDelete(Nullable<int> id_ficha_marketing)
        {
            var id_ficha_marketingParameter = id_ficha_marketing.HasValue ?
                new ObjectParameter("id_ficha_marketing", id_ficha_marketing) :
                new ObjectParameter("id_ficha_marketing", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FichaMarketingDelete", id_ficha_marketingParameter);
        }
    
        public virtual int FichaMarketingEliminar(Nullable<int> id_ficha_marketing)
        {
            var id_ficha_marketingParameter = id_ficha_marketing.HasValue ?
                new ObjectParameter("id_ficha_marketing", id_ficha_marketing) :
                new ObjectParameter("id_ficha_marketing", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FichaMarketingEliminar", id_ficha_marketingParameter);
        }
    
        public virtual int FichaMarketingNew(Nullable<int> id_ficha_marketing, Nullable<int> id_persona_fuente, Nullable<short> forma_contacto_inical, Nullable<short> primer_interes, Nullable<System.DateTime> fecha_primer_contacto, Nullable<System.DateTime> fecha_ultimo_contacto)
        {
            var id_ficha_marketingParameter = id_ficha_marketing.HasValue ?
                new ObjectParameter("id_ficha_marketing", id_ficha_marketing) :
                new ObjectParameter("id_ficha_marketing", typeof(int));
    
            var id_persona_fuenteParameter = id_persona_fuente.HasValue ?
                new ObjectParameter("id_persona_fuente", id_persona_fuente) :
                new ObjectParameter("id_persona_fuente", typeof(int));
    
            var forma_contacto_inicalParameter = forma_contacto_inical.HasValue ?
                new ObjectParameter("forma_contacto_inical", forma_contacto_inical) :
                new ObjectParameter("forma_contacto_inical", typeof(short));
    
            var primer_interesParameter = primer_interes.HasValue ?
                new ObjectParameter("primer_interes", primer_interes) :
                new ObjectParameter("primer_interes", typeof(short));
    
            var fecha_primer_contactoParameter = fecha_primer_contacto.HasValue ?
                new ObjectParameter("fecha_primer_contacto", fecha_primer_contacto) :
                new ObjectParameter("fecha_primer_contacto", typeof(System.DateTime));
    
            var fecha_ultimo_contactoParameter = fecha_ultimo_contacto.HasValue ?
                new ObjectParameter("fecha_ultimo_contacto", fecha_ultimo_contacto) :
                new ObjectParameter("fecha_ultimo_contacto", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FichaMarketingNew", id_ficha_marketingParameter, id_persona_fuenteParameter, forma_contacto_inicalParameter, primer_interesParameter, fecha_primer_contactoParameter, fecha_ultimo_contactoParameter);
        }
    
        public virtual ObjectResult<ListarContactoInicial_Result> ListarContactoInicial()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarContactoInicial_Result>("ListarContactoInicial");
        }
    
        public virtual ObjectResult<ListarFichaMarketingPorId_Result> ListarFichaMarketingPorId(Nullable<int> id_ficha_marketing)
        {
            var id_ficha_marketingParameter = id_ficha_marketing.HasValue ?
                new ObjectParameter("id_ficha_marketing", id_ficha_marketing) :
                new ObjectParameter("id_ficha_marketing", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarFichaMarketingPorId_Result>("ListarFichaMarketingPorId", id_ficha_marketingParameter);
        }
    
        public virtual ObjectResult<ListarPrimerInteres_Result> ListarPrimerInteres()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarPrimerInteres_Result>("ListarPrimerInteres");
        }
    
        public virtual int ClienteNew(Nullable<int> id_persona, Nullable<int> marketing, string nom_cliente, string doc_oficial)
        {
            var id_personaParameter = id_persona.HasValue ?
                new ObjectParameter("id_persona", id_persona) :
                new ObjectParameter("id_persona", typeof(int));
    
            var marketingParameter = marketing.HasValue ?
                new ObjectParameter("marketing", marketing) :
                new ObjectParameter("marketing", typeof(int));
    
            var nom_clienteParameter = nom_cliente != null ?
                new ObjectParameter("nom_cliente", nom_cliente) :
                new ObjectParameter("nom_cliente", typeof(string));
    
            var doc_oficialParameter = doc_oficial != null ?
                new ObjectParameter("doc_oficial", doc_oficial) :
                new ObjectParameter("doc_oficial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ClienteNew", id_personaParameter, marketingParameter, nom_clienteParameter, doc_oficialParameter);
        }
    
        public virtual int CredentialNew(string usuario, string password, string salt, Nullable<bool> active, Nullable<int> empleado)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var saltParameter = salt != null ?
                new ObjectParameter("salt", salt) :
                new ObjectParameter("salt", typeof(string));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(bool));
    
            var empleadoParameter = empleado.HasValue ?
                new ObjectParameter("empleado", empleado) :
                new ObjectParameter("empleado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CredentialNew", usuarioParameter, passwordParameter, saltParameter, activeParameter, empleadoParameter);
        }
    
        public virtual ObjectResult<CredentialSelect_Result> CredentialSelect(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CredentialSelect_Result>("CredentialSelect", usuarioParameter);
        }
    
        public virtual int CredentialUpdate(Nullable<int> id_usuario, string usuario, string password, string salt, Nullable<bool> active, Nullable<int> empleado)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var saltParameter = salt != null ?
                new ObjectParameter("salt", salt) :
                new ObjectParameter("salt", typeof(string));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(bool));
    
            var empleadoParameter = empleado.HasValue ?
                new ObjectParameter("empleado", empleado) :
                new ObjectParameter("empleado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CredentialUpdate", id_usuarioParameter, usuarioParameter, passwordParameter, saltParameter, activeParameter, empleadoParameter);
        }
    
        public virtual int DireccionNew(Nullable<byte> tipo_direccion, Nullable<int> id_persona, Nullable<byte> dir_pais, Nullable<int> dir_provincia, Nullable<int> dir_ciudad, Nullable<int> dir_distrito, string dir_linea_1, string dir_linea_2, string dir_codigo_postal)
        {
            var tipo_direccionParameter = tipo_direccion.HasValue ?
                new ObjectParameter("tipo_direccion", tipo_direccion) :
                new ObjectParameter("tipo_direccion", typeof(byte));
    
            var id_personaParameter = id_persona.HasValue ?
                new ObjectParameter("id_persona", id_persona) :
                new ObjectParameter("id_persona", typeof(int));
    
            var dir_paisParameter = dir_pais.HasValue ?
                new ObjectParameter("dir_pais", dir_pais) :
                new ObjectParameter("dir_pais", typeof(byte));
    
            var dir_provinciaParameter = dir_provincia.HasValue ?
                new ObjectParameter("dir_provincia", dir_provincia) :
                new ObjectParameter("dir_provincia", typeof(int));
    
            var dir_ciudadParameter = dir_ciudad.HasValue ?
                new ObjectParameter("dir_ciudad", dir_ciudad) :
                new ObjectParameter("dir_ciudad", typeof(int));
    
            var dir_distritoParameter = dir_distrito.HasValue ?
                new ObjectParameter("dir_distrito", dir_distrito) :
                new ObjectParameter("dir_distrito", typeof(int));
    
            var dir_linea_1Parameter = dir_linea_1 != null ?
                new ObjectParameter("dir_linea_1", dir_linea_1) :
                new ObjectParameter("dir_linea_1", typeof(string));
    
            var dir_linea_2Parameter = dir_linea_2 != null ?
                new ObjectParameter("dir_linea_2", dir_linea_2) :
                new ObjectParameter("dir_linea_2", typeof(string));
    
            var dir_codigo_postalParameter = dir_codigo_postal != null ?
                new ObjectParameter("dir_codigo_postal", dir_codigo_postal) :
                new ObjectParameter("dir_codigo_postal", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DireccionNew", tipo_direccionParameter, id_personaParameter, dir_paisParameter, dir_provinciaParameter, dir_ciudadParameter, dir_distritoParameter, dir_linea_1Parameter, dir_linea_2Parameter, dir_codigo_postalParameter);
        }
    
        public virtual int EliminarCliente(Nullable<int> id_persona, Nullable<int> id_ficha_marketing)
        {
            var id_personaParameter = id_persona.HasValue ?
                new ObjectParameter("id_persona", id_persona) :
                new ObjectParameter("id_persona", typeof(int));
    
            var id_ficha_marketingParameter = id_ficha_marketing.HasValue ?
                new ObjectParameter("id_ficha_marketing", id_ficha_marketing) :
                new ObjectParameter("id_ficha_marketing", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarCliente", id_personaParameter, id_ficha_marketingParameter);
        }
    
        public virtual int EliminarCredencial(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarCredencial", usuarioParameter);
        }
    
        public virtual int EliminarDireccion(Nullable<int> id_direccion)
        {
            var id_direccionParameter = id_direccion.HasValue ?
                new ObjectParameter("id_direccion", id_direccion) :
                new ObjectParameter("id_direccion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarDireccion", id_direccionParameter);
        }
    
        public virtual int EliminarEmail(Nullable<int> id_email)
        {
            var id_emailParameter = id_email.HasValue ?
                new ObjectParameter("id_email", id_email) :
                new ObjectParameter("id_email", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarEmail", id_emailParameter);
        }
    
        public virtual int EliminarEmpleado(Nullable<int> id_persona)
        {
            var id_personaParameter = id_persona.HasValue ?
                new ObjectParameter("id_persona", id_persona) :
                new ObjectParameter("id_persona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarEmpleado", id_personaParameter);
        }
    
        public virtual int EliminarPersonaDeInteres(Nullable<int> id_persona)
        {
            var id_personaParameter = id_persona.HasValue ?
                new ObjectParameter("id_persona", id_persona) :
                new ObjectParameter("id_persona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarPersonaDeInteres", id_personaParameter);
        }
    
        public virtual int EliminarTelefono(Nullable<int> id_telefono)
        {
            var id_telefonoParameter = id_telefono.HasValue ?
                new ObjectParameter("id_telefono", id_telefono) :
                new ObjectParameter("id_telefono", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarTelefono", id_telefonoParameter);
        }
    
        public virtual int EmailNew(Nullable<byte> tipo_email, Nullable<int> id_persona, string direccion_email)
        {
            var tipo_emailParameter = tipo_email.HasValue ?
                new ObjectParameter("tipo_email", tipo_email) :
                new ObjectParameter("tipo_email", typeof(byte));
    
            var id_personaParameter = id_persona.HasValue ?
                new ObjectParameter("id_persona", id_persona) :
                new ObjectParameter("id_persona", typeof(int));
    
            var direccion_emailParameter = direccion_email != null ?
                new ObjectParameter("direccion_email", direccion_email) :
                new ObjectParameter("direccion_email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EmailNew", tipo_emailParameter, id_personaParameter, direccion_emailParameter);
        }
    
        public virtual int EmpleadoSelectEstado(Nullable<int> id_persona, ObjectParameter estado)
        {
            var id_personaParameter = id_persona.HasValue ?
                new ObjectParameter("id_persona", id_persona) :
                new ObjectParameter("id_persona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EmpleadoSelectEstado", id_personaParameter, estado);
        }
    
        public virtual int LestarTelefonosFull()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LestarTelefonosFull");
        }
    
        public virtual int LestarTelefonosFullPorId(Nullable<int> id_persona)
        {
            var id_personaParameter = id_persona.HasValue ?
                new ObjectParameter("id_persona", id_persona) :
                new ObjectParameter("id_persona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LestarTelefonosFullPorId", id_personaParameter);
        }
    
        public virtual ObjectResult<ListarCiudades_Result> ListarCiudades()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarCiudades_Result>("ListarCiudades");
        }
    
        public virtual ObjectResult<ListarCiudadesPorIdRegion_Result> ListarCiudadesPorIdRegion(Nullable<int> id_region)
        {
            var id_regionParameter = id_region.HasValue ?
                new ObjectParameter("id_region", id_region) :
                new ObjectParameter("id_region", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarCiudadesPorIdRegion_Result>("ListarCiudadesPorIdRegion", id_regionParameter);
        }
    
        public virtual ObjectResult<ListarClientes_Result> ListarClientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarClientes_Result>("ListarClientes");
        }
    
        public virtual ObjectResult<ListarClientesFull_Result> ListarClientesFull()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarClientesFull_Result>("ListarClientesFull");
        }
    
        public virtual ObjectResult<ListarClientesPorId_Result> ListarClientesPorId(Nullable<int> id_persona)
        {
            var id_personaParameter = id_persona.HasValue ?
                new ObjectParameter("id_persona", id_persona) :
                new ObjectParameter("id_persona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarClientesPorId_Result>("ListarClientesPorId", id_personaParameter);
        }
    
        public virtual ObjectResult<ListarCredenciales_Result> ListarCredenciales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarCredenciales_Result>("ListarCredenciales");
        }
    
        public virtual int ListarDireccionesFull()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListarDireccionesFull");
        }
    
        public virtual int ListarDireccionesFullPorId(Nullable<int> id_persona)
        {
            var id_personaParameter = id_persona.HasValue ?
                new ObjectParameter("id_persona", id_persona) :
                new ObjectParameter("id_persona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListarDireccionesFullPorId", id_personaParameter);
        }
    
        public virtual ObjectResult<ListarDireccionesTipos_Result> ListarDireccionesTipos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarDireccionesTipos_Result>("ListarDireccionesTipos");
        }
    
        public virtual ObjectResult<ListarDistritoPorIdPorCiudad_Result> ListarDistritoPorIdPorCiudad(Nullable<int> id_ciudad)
        {
            var id_ciudadParameter = id_ciudad.HasValue ?
                new ObjectParameter("id_ciudad", id_ciudad) :
                new ObjectParameter("id_ciudad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarDistritoPorIdPorCiudad_Result>("ListarDistritoPorIdPorCiudad", id_ciudadParameter);
        }
    
        public virtual ObjectResult<ListarDistritos_Result> ListarDistritos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarDistritos_Result>("ListarDistritos");
        }
    
        public virtual ObjectResult<ListarEmailsTipos_Result> ListarEmailsTipos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarEmailsTipos_Result>("ListarEmailsTipos");
        }
    
        public virtual ObjectResult<ListarEMpleadoFull_Result> ListarEMpleadoFull()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarEMpleadoFull_Result>("ListarEMpleadoFull");
        }
    
        public virtual ObjectResult<ListarEmpleadoPorId_Result> ListarEmpleadoPorId(Nullable<int> id_persona)
        {
            var id_personaParameter = id_persona.HasValue ?
                new ObjectParameter("id_persona", id_persona) :
                new ObjectParameter("id_persona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarEmpleadoPorId_Result>("ListarEmpleadoPorId", id_personaParameter);
        }
    
        public virtual ObjectResult<ListarEmpleados_Result> ListarEmpleados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarEmpleados_Result>("ListarEmpleados");
        }
    
        public virtual ObjectResult<ListarPaises_Result> ListarPaises()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarPaises_Result>("ListarPaises");
        }
    
        public virtual int ListarPersonasConDirecciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListarPersonasConDirecciones");
        }
    
        public virtual ObjectResult<ListarPersonasDeInteres_Result> ListarPersonasDeInteres()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarPersonasDeInteres_Result>("ListarPersonasDeInteres");
        }
    
        public virtual ObjectResult<ListarPersonasDeInteresPorId_Result> ListarPersonasDeInteresPorId(Nullable<int> id_persona)
        {
            var id_personaParameter = id_persona.HasValue ?
                new ObjectParameter("id_persona", id_persona) :
                new ObjectParameter("id_persona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarPersonasDeInteresPorId_Result>("ListarPersonasDeInteresPorId", id_personaParameter);
        }
    
        public virtual ObjectResult<ListarPersonasFull_Result> ListarPersonasFull()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarPersonasFull_Result>("ListarPersonasFull");
        }
    
        public virtual ObjectResult<ListarProyecto_Result> ListarProyecto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarProyecto_Result>("ListarProyecto");
        }
    
        public virtual ObjectResult<ListarPuestos_Result> ListarPuestos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarPuestos_Result>("ListarPuestos");
        }
    
        public virtual ObjectResult<ListarRegiones_Result> ListarRegiones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarRegiones_Result>("ListarRegiones");
        }
    
        public virtual ObjectResult<ListarRegionesPorIdPais_Result> ListarRegionesPorIdPais(Nullable<int> id_pais)
        {
            var id_paisParameter = id_pais.HasValue ?
                new ObjectParameter("id_pais", id_pais) :
                new ObjectParameter("id_pais", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarRegionesPorIdPais_Result>("ListarRegionesPorIdPais", id_paisParameter);
        }
    
        public virtual ObjectResult<ListarTelefonosPorPersona_Result> ListarTelefonosPorPersona(Nullable<int> id_persona)
        {
            var id_personaParameter = id_persona.HasValue ?
                new ObjectParameter("id_persona", id_persona) :
                new ObjectParameter("id_persona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarTelefonosPorPersona_Result>("ListarTelefonosPorPersona", id_personaParameter);
        }
    
        public virtual ObjectResult<ListarTelefonosTipos_Result> ListarTelefonosTipos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarTelefonosTipos_Result>("ListarTelefonosTipos");
        }
    
        public virtual int ModificarCliente(Nullable<int> id_persona, Nullable<int> marketing, string nom_cliente, string doc_oficial)
        {
            var id_personaParameter = id_persona.HasValue ?
                new ObjectParameter("id_persona", id_persona) :
                new ObjectParameter("id_persona", typeof(int));
    
            var marketingParameter = marketing.HasValue ?
                new ObjectParameter("marketing", marketing) :
                new ObjectParameter("marketing", typeof(int));
    
            var nom_clienteParameter = nom_cliente != null ?
                new ObjectParameter("nom_cliente", nom_cliente) :
                new ObjectParameter("nom_cliente", typeof(string));
    
            var doc_oficialParameter = doc_oficial != null ?
                new ObjectParameter("doc_oficial", doc_oficial) :
                new ObjectParameter("doc_oficial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificarCliente", id_personaParameter, marketingParameter, nom_clienteParameter, doc_oficialParameter);
        }
    
        public virtual int ModificarDireccion(Nullable<int> id_direccion, Nullable<byte> tipo_direccion, Nullable<int> id_persona, Nullable<byte> dir_pais, Nullable<int> dir_provincia, Nullable<int> dir_ciudad, Nullable<int> dir_distrito, string dir_linea_1, string dir_linea_2, string dir_codigo_postal)
        {
            var id_direccionParameter = id_direccion.HasValue ?
                new ObjectParameter("id_direccion", id_direccion) :
                new ObjectParameter("id_direccion", typeof(int));
    
            var tipo_direccionParameter = tipo_direccion.HasValue ?
                new ObjectParameter("tipo_direccion", tipo_direccion) :
                new ObjectParameter("tipo_direccion", typeof(byte));
    
            var id_personaParameter = id_persona.HasValue ?
                new ObjectParameter("id_persona", id_persona) :
                new ObjectParameter("id_persona", typeof(int));
    
            var dir_paisParameter = dir_pais.HasValue ?
                new ObjectParameter("dir_pais", dir_pais) :
                new ObjectParameter("dir_pais", typeof(byte));
    
            var dir_provinciaParameter = dir_provincia.HasValue ?
                new ObjectParameter("dir_provincia", dir_provincia) :
                new ObjectParameter("dir_provincia", typeof(int));
    
            var dir_ciudadParameter = dir_ciudad.HasValue ?
                new ObjectParameter("dir_ciudad", dir_ciudad) :
                new ObjectParameter("dir_ciudad", typeof(int));
    
            var dir_distritoParameter = dir_distrito.HasValue ?
                new ObjectParameter("dir_distrito", dir_distrito) :
                new ObjectParameter("dir_distrito", typeof(int));
    
            var dir_linea_1Parameter = dir_linea_1 != null ?
                new ObjectParameter("dir_linea_1", dir_linea_1) :
                new ObjectParameter("dir_linea_1", typeof(string));
    
            var dir_linea_2Parameter = dir_linea_2 != null ?
                new ObjectParameter("dir_linea_2", dir_linea_2) :
                new ObjectParameter("dir_linea_2", typeof(string));
    
            var dir_codigo_postalParameter = dir_codigo_postal != null ?
                new ObjectParameter("dir_codigo_postal", dir_codigo_postal) :
                new ObjectParameter("dir_codigo_postal", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificarDireccion", id_direccionParameter, tipo_direccionParameter, id_personaParameter, dir_paisParameter, dir_provinciaParameter, dir_ciudadParameter, dir_distritoParameter, dir_linea_1Parameter, dir_linea_2Parameter, dir_codigo_postalParameter);
        }
    
        public virtual int ModificarEmail(Nullable<byte> tipo_email, Nullable<int> id_email, Nullable<int> id_persona, string direccion_email)
        {
            var tipo_emailParameter = tipo_email.HasValue ?
                new ObjectParameter("tipo_email", tipo_email) :
                new ObjectParameter("tipo_email", typeof(byte));
    
            var id_emailParameter = id_email.HasValue ?
                new ObjectParameter("id_email", id_email) :
                new ObjectParameter("id_email", typeof(int));
    
            var id_personaParameter = id_persona.HasValue ?
                new ObjectParameter("id_persona", id_persona) :
                new ObjectParameter("id_persona", typeof(int));
    
            var direccion_emailParameter = direccion_email != null ?
                new ObjectParameter("direccion_email", direccion_email) :
                new ObjectParameter("direccion_email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificarEmail", tipo_emailParameter, id_emailParameter, id_personaParameter, direccion_emailParameter);
        }
    
        public virtual int ModificarEmpleado(Nullable<int> id_persona, Nullable<short> puesto_empleado, string doc_oficial, string ruc_empleado, Nullable<System.DateTime> fecha_nacimiento, Nullable<System.DateTime> fecha_inicio, string primer_nom, string segundo_nom, string primer_ape, string segundo_ape)
        {
            var id_personaParameter = id_persona.HasValue ?
                new ObjectParameter("id_persona", id_persona) :
                new ObjectParameter("id_persona", typeof(int));
    
            var puesto_empleadoParameter = puesto_empleado.HasValue ?
                new ObjectParameter("puesto_empleado", puesto_empleado) :
                new ObjectParameter("puesto_empleado", typeof(short));
    
            var doc_oficialParameter = doc_oficial != null ?
                new ObjectParameter("doc_oficial", doc_oficial) :
                new ObjectParameter("doc_oficial", typeof(string));
    
            var ruc_empleadoParameter = ruc_empleado != null ?
                new ObjectParameter("ruc_empleado", ruc_empleado) :
                new ObjectParameter("ruc_empleado", typeof(string));
    
            var fecha_nacimientoParameter = fecha_nacimiento.HasValue ?
                new ObjectParameter("fecha_nacimiento", fecha_nacimiento) :
                new ObjectParameter("fecha_nacimiento", typeof(System.DateTime));
    
            var fecha_inicioParameter = fecha_inicio.HasValue ?
                new ObjectParameter("fecha_inicio", fecha_inicio) :
                new ObjectParameter("fecha_inicio", typeof(System.DateTime));
    
            var primer_nomParameter = primer_nom != null ?
                new ObjectParameter("primer_nom", primer_nom) :
                new ObjectParameter("primer_nom", typeof(string));
    
            var segundo_nomParameter = segundo_nom != null ?
                new ObjectParameter("segundo_nom", segundo_nom) :
                new ObjectParameter("segundo_nom", typeof(string));
    
            var primer_apeParameter = primer_ape != null ?
                new ObjectParameter("primer_ape", primer_ape) :
                new ObjectParameter("primer_ape", typeof(string));
    
            var segundo_apeParameter = segundo_ape != null ?
                new ObjectParameter("segundo_ape", segundo_ape) :
                new ObjectParameter("segundo_ape", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificarEmpleado", id_personaParameter, puesto_empleadoParameter, doc_oficialParameter, ruc_empleadoParameter, fecha_nacimientoParameter, fecha_inicioParameter, primer_nomParameter, segundo_nomParameter, primer_apeParameter, segundo_apeParameter);
        }
    
        public virtual int ModificarTelefono(Nullable<int> id_telefono, Nullable<byte> tipo_telefono, string codigo_pais, string campo_1, string campo_2, string campo_3, string ext)
        {
            var id_telefonoParameter = id_telefono.HasValue ?
                new ObjectParameter("id_telefono", id_telefono) :
                new ObjectParameter("id_telefono", typeof(int));
    
            var tipo_telefonoParameter = tipo_telefono.HasValue ?
                new ObjectParameter("tipo_telefono", tipo_telefono) :
                new ObjectParameter("tipo_telefono", typeof(byte));
    
            var codigo_paisParameter = codigo_pais != null ?
                new ObjectParameter("codigo_pais", codigo_pais) :
                new ObjectParameter("codigo_pais", typeof(string));
    
            var campo_1Parameter = campo_1 != null ?
                new ObjectParameter("campo_1", campo_1) :
                new ObjectParameter("campo_1", typeof(string));
    
            var campo_2Parameter = campo_2 != null ?
                new ObjectParameter("campo_2", campo_2) :
                new ObjectParameter("campo_2", typeof(string));
    
            var campo_3Parameter = campo_3 != null ?
                new ObjectParameter("campo_3", campo_3) :
                new ObjectParameter("campo_3", typeof(string));
    
            var extParameter = ext != null ?
                new ObjectParameter("ext", ext) :
                new ObjectParameter("ext", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificarTelefono", id_telefonoParameter, tipo_telefonoParameter, codigo_paisParameter, campo_1Parameter, campo_2Parameter, campo_3Parameter, extParameter);
        }
    
        public virtual int NewEmpleado(Nullable<int> id_persona, Nullable<short> puesto_empleado, string doc_oficial, string ruc_empleado, Nullable<System.DateTime> fecha_nacimiento, Nullable<System.DateTime> fecha_inicio, string primer_nom, string segundo_nom, string primer_ape, string segundo_ape, Nullable<bool> estado)
        {
            var id_personaParameter = id_persona.HasValue ?
                new ObjectParameter("id_persona", id_persona) :
                new ObjectParameter("id_persona", typeof(int));
    
            var puesto_empleadoParameter = puesto_empleado.HasValue ?
                new ObjectParameter("puesto_empleado", puesto_empleado) :
                new ObjectParameter("puesto_empleado", typeof(short));
    
            var doc_oficialParameter = doc_oficial != null ?
                new ObjectParameter("doc_oficial", doc_oficial) :
                new ObjectParameter("doc_oficial", typeof(string));
    
            var ruc_empleadoParameter = ruc_empleado != null ?
                new ObjectParameter("ruc_empleado", ruc_empleado) :
                new ObjectParameter("ruc_empleado", typeof(string));
    
            var fecha_nacimientoParameter = fecha_nacimiento.HasValue ?
                new ObjectParameter("fecha_nacimiento", fecha_nacimiento) :
                new ObjectParameter("fecha_nacimiento", typeof(System.DateTime));
    
            var fecha_inicioParameter = fecha_inicio.HasValue ?
                new ObjectParameter("fecha_inicio", fecha_inicio) :
                new ObjectParameter("fecha_inicio", typeof(System.DateTime));
    
            var primer_nomParameter = primer_nom != null ?
                new ObjectParameter("primer_nom", primer_nom) :
                new ObjectParameter("primer_nom", typeof(string));
    
            var segundo_nomParameter = segundo_nom != null ?
                new ObjectParameter("segundo_nom", segundo_nom) :
                new ObjectParameter("segundo_nom", typeof(string));
    
            var primer_apeParameter = primer_ape != null ?
                new ObjectParameter("primer_ape", primer_ape) :
                new ObjectParameter("primer_ape", typeof(string));
    
            var segundo_apeParameter = segundo_ape != null ?
                new ObjectParameter("segundo_ape", segundo_ape) :
                new ObjectParameter("segundo_ape", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NewEmpleado", id_personaParameter, puesto_empleadoParameter, doc_oficialParameter, ruc_empleadoParameter, fecha_nacimientoParameter, fecha_inicioParameter, primer_nomParameter, segundo_nomParameter, primer_apeParameter, segundo_apeParameter, estadoParameter);
        }
    
        public virtual int NuevoCliente(Nullable<int> ficha_marketing, string nom_cliente, string doc_oficial)
        {
            var ficha_marketingParameter = ficha_marketing.HasValue ?
                new ObjectParameter("ficha_marketing", ficha_marketing) :
                new ObjectParameter("ficha_marketing", typeof(int));
    
            var nom_clienteParameter = nom_cliente != null ?
                new ObjectParameter("nom_cliente", nom_cliente) :
                new ObjectParameter("nom_cliente", typeof(string));
    
            var doc_oficialParameter = doc_oficial != null ?
                new ObjectParameter("doc_oficial", doc_oficial) :
                new ObjectParameter("doc_oficial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NuevoCliente", ficha_marketingParameter, nom_clienteParameter, doc_oficialParameter);
        }
    
        public virtual int NuevoEmpleado(Nullable<int> puesto, string doc_oficial, string ruc, Nullable<System.DateTime> fecha_nac, Nullable<System.DateTime> fecha_inicio, string primer_nom, string primer_ape, string segundo_nom, string segundo_ape)
        {
            var puestoParameter = puesto.HasValue ?
                new ObjectParameter("puesto", puesto) :
                new ObjectParameter("puesto", typeof(int));
    
            var doc_oficialParameter = doc_oficial != null ?
                new ObjectParameter("doc_oficial", doc_oficial) :
                new ObjectParameter("doc_oficial", typeof(string));
    
            var rucParameter = ruc != null ?
                new ObjectParameter("ruc", ruc) :
                new ObjectParameter("ruc", typeof(string));
    
            var fecha_nacParameter = fecha_nac.HasValue ?
                new ObjectParameter("fecha_nac", fecha_nac) :
                new ObjectParameter("fecha_nac", typeof(System.DateTime));
    
            var fecha_inicioParameter = fecha_inicio.HasValue ?
                new ObjectParameter("fecha_inicio", fecha_inicio) :
                new ObjectParameter("fecha_inicio", typeof(System.DateTime));
    
            var primer_nomParameter = primer_nom != null ?
                new ObjectParameter("primer_nom", primer_nom) :
                new ObjectParameter("primer_nom", typeof(string));
    
            var primer_apeParameter = primer_ape != null ?
                new ObjectParameter("primer_ape", primer_ape) :
                new ObjectParameter("primer_ape", typeof(string));
    
            var segundo_nomParameter = segundo_nom != null ?
                new ObjectParameter("segundo_nom", segundo_nom) :
                new ObjectParameter("segundo_nom", typeof(string));
    
            var segundo_apeParameter = segundo_ape != null ?
                new ObjectParameter("segundo_ape", segundo_ape) :
                new ObjectParameter("segundo_ape", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NuevoEmpleado", puestoParameter, doc_oficialParameter, rucParameter, fecha_nacParameter, fecha_inicioParameter, primer_nomParameter, primer_apeParameter, segundo_nomParameter, segundo_apeParameter);
        }
    
        public virtual int PersonaDeInteresNew(Nullable<int> id_persona, Nullable<int> id_directorio, Nullable<int> id_proyecto, Nullable<short> puesto, string nom_persona)
        {
            var id_personaParameter = id_persona.HasValue ?
                new ObjectParameter("id_persona", id_persona) :
                new ObjectParameter("id_persona", typeof(int));
    
            var id_directorioParameter = id_directorio.HasValue ?
                new ObjectParameter("id_directorio", id_directorio) :
                new ObjectParameter("id_directorio", typeof(int));
    
            var id_proyectoParameter = id_proyecto.HasValue ?
                new ObjectParameter("id_proyecto", id_proyecto) :
                new ObjectParameter("id_proyecto", typeof(int));
    
            var puestoParameter = puesto.HasValue ?
                new ObjectParameter("puesto", puesto) :
                new ObjectParameter("puesto", typeof(short));
    
            var nom_personaParameter = nom_persona != null ?
                new ObjectParameter("nom_persona", nom_persona) :
                new ObjectParameter("nom_persona", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PersonaDeInteresNew", id_personaParameter, id_directorioParameter, id_proyectoParameter, puestoParameter, nom_personaParameter);
        }
    
        public virtual ObjectResult<SelectDireccion_Result> SelectDireccion(Nullable<int> id_direccion)
        {
            var id_direccionParameter = id_direccion.HasValue ?
                new ObjectParameter("id_direccion", id_direccion) :
                new ObjectParameter("id_direccion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectDireccion_Result>("SelectDireccion", id_direccionParameter);
        }
    
        public virtual ObjectResult<SelectEmail_Result> SelectEmail(Nullable<int> id_email)
        {
            var id_emailParameter = id_email.HasValue ?
                new ObjectParameter("id_email", id_email) :
                new ObjectParameter("id_email", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectEmail_Result>("SelectEmail", id_emailParameter);
        }
    
        public virtual ObjectResult<SelectTelefono_Result> SelectTelefono(Nullable<int> id_telefono)
        {
            var id_telefonoParameter = id_telefono.HasValue ?
                new ObjectParameter("id_telefono", id_telefono) :
                new ObjectParameter("id_telefono", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectTelefono_Result>("SelectTelefono", id_telefonoParameter);
        }
    
        public virtual int TelefonoNew(Nullable<int> id_persona, Nullable<byte> tipo_telefono, string codigo_pais, string campo_1, string campo_2, string campo_3, string ext)
        {
            var id_personaParameter = id_persona.HasValue ?
                new ObjectParameter("id_persona", id_persona) :
                new ObjectParameter("id_persona", typeof(int));
    
            var tipo_telefonoParameter = tipo_telefono.HasValue ?
                new ObjectParameter("tipo_telefono", tipo_telefono) :
                new ObjectParameter("tipo_telefono", typeof(byte));
    
            var codigo_paisParameter = codigo_pais != null ?
                new ObjectParameter("codigo_pais", codigo_pais) :
                new ObjectParameter("codigo_pais", typeof(string));
    
            var campo_1Parameter = campo_1 != null ?
                new ObjectParameter("campo_1", campo_1) :
                new ObjectParameter("campo_1", typeof(string));
    
            var campo_2Parameter = campo_2 != null ?
                new ObjectParameter("campo_2", campo_2) :
                new ObjectParameter("campo_2", typeof(string));
    
            var campo_3Parameter = campo_3 != null ?
                new ObjectParameter("campo_3", campo_3) :
                new ObjectParameter("campo_3", typeof(string));
    
            var extParameter = ext != null ?
                new ObjectParameter("ext", ext) :
                new ObjectParameter("ext", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TelefonoNew", id_personaParameter, tipo_telefonoParameter, codigo_paisParameter, campo_1Parameter, campo_2Parameter, campo_3Parameter, extParameter);
        }
    
        public virtual int UpdateEstado(Nullable<int> id_persona, Nullable<bool> estado)
        {
            var id_personaParameter = id_persona.HasValue ?
                new ObjectParameter("id_persona", id_persona) :
                new ObjectParameter("id_persona", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateEstado", id_personaParameter, estadoParameter);
        }
    
        public virtual int UpdatePersonaInteres(Nullable<int> id_persona, Nullable<int> id_directorio, Nullable<int> id_proyecto, Nullable<short> puesto, string nom_persona)
        {
            var id_personaParameter = id_persona.HasValue ?
                new ObjectParameter("id_persona", id_persona) :
                new ObjectParameter("id_persona", typeof(int));
    
            var id_directorioParameter = id_directorio.HasValue ?
                new ObjectParameter("id_directorio", id_directorio) :
                new ObjectParameter("id_directorio", typeof(int));
    
            var id_proyectoParameter = id_proyecto.HasValue ?
                new ObjectParameter("id_proyecto", id_proyecto) :
                new ObjectParameter("id_proyecto", typeof(int));
    
            var puestoParameter = puesto.HasValue ?
                new ObjectParameter("puesto", puesto) :
                new ObjectParameter("puesto", typeof(short));
    
            var nom_personaParameter = nom_persona != null ?
                new ObjectParameter("nom_persona", nom_persona) :
                new ObjectParameter("nom_persona", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdatePersonaInteres", id_personaParameter, id_directorioParameter, id_proyectoParameter, puestoParameter, nom_personaParameter);
        }
    
        public virtual int FinalizarProyecto(Nullable<System.DateTime> fechaFin, Nullable<int> id_proyecto)
        {
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var id_proyectoParameter = id_proyecto.HasValue ?
                new ObjectParameter("id_proyecto", id_proyecto) :
                new ObjectParameter("id_proyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FinalizarProyecto", fechaFinParameter, id_proyectoParameter);
        }
    
        public virtual ObjectResult<ListarDivisiones_Result> ListarDivisiones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarDivisiones_Result>("ListarDivisiones");
        }
    
        public virtual ObjectResult<ListarProyectoPorId_Result> ListarProyectoPorId(Nullable<int> id_proyecto)
        {
            var id_proyectoParameter = id_proyecto.HasValue ?
                new ObjectParameter("id_proyecto", id_proyecto) :
                new ObjectParameter("id_proyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarProyectoPorId_Result>("ListarProyectoPorId", id_proyectoParameter);
        }
    
        public virtual ObjectResult<ListarProyectos_Result> ListarProyectos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarProyectos_Result>("ListarProyectos");
        }
    
        public virtual int NuevoProyecto(Nullable<int> id_cliente, Nullable<byte> id_division, string nom_proyecto, Nullable<int> dir_proyecto, Nullable<System.DateTime> fecha_inicio)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            var id_divisionParameter = id_division.HasValue ?
                new ObjectParameter("id_division", id_division) :
                new ObjectParameter("id_division", typeof(byte));
    
            var nom_proyectoParameter = nom_proyecto != null ?
                new ObjectParameter("nom_proyecto", nom_proyecto) :
                new ObjectParameter("nom_proyecto", typeof(string));
    
            var dir_proyectoParameter = dir_proyecto.HasValue ?
                new ObjectParameter("dir_proyecto", dir_proyecto) :
                new ObjectParameter("dir_proyecto", typeof(int));
    
            var fecha_inicioParameter = fecha_inicio.HasValue ?
                new ObjectParameter("fecha_inicio", fecha_inicio) :
                new ObjectParameter("fecha_inicio", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NuevoProyecto", id_clienteParameter, id_divisionParameter, nom_proyectoParameter, dir_proyectoParameter, fecha_inicioParameter);
        }
    
        public virtual int ProyectoNew(Nullable<int> id_cliente, Nullable<byte> id_division, string nom_proyecto, string dir_proyecto, Nullable<System.DateTime> fecha_inicio)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            var id_divisionParameter = id_division.HasValue ?
                new ObjectParameter("id_division", id_division) :
                new ObjectParameter("id_division", typeof(byte));
    
            var nom_proyectoParameter = nom_proyecto != null ?
                new ObjectParameter("nom_proyecto", nom_proyecto) :
                new ObjectParameter("nom_proyecto", typeof(string));
    
            var dir_proyectoParameter = dir_proyecto != null ?
                new ObjectParameter("dir_proyecto", dir_proyecto) :
                new ObjectParameter("dir_proyecto", typeof(string));
    
            var fecha_inicioParameter = fecha_inicio.HasValue ?
                new ObjectParameter("fecha_inicio", fecha_inicio) :
                new ObjectParameter("fecha_inicio", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProyectoNew", id_clienteParameter, id_divisionParameter, nom_proyectoParameter, dir_proyectoParameter, fecha_inicioParameter);
        }
    
        public virtual int UpdateProyecto(Nullable<int> id_proyecto, Nullable<int> id_cliente, Nullable<byte> id_division, string nom_proyecto, string dir_proyecto, Nullable<System.DateTime> fecha_inicio, Nullable<System.DateTime> fecha_fin)
        {
            var id_proyectoParameter = id_proyecto.HasValue ?
                new ObjectParameter("id_proyecto", id_proyecto) :
                new ObjectParameter("id_proyecto", typeof(int));
    
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            var id_divisionParameter = id_division.HasValue ?
                new ObjectParameter("id_division", id_division) :
                new ObjectParameter("id_division", typeof(byte));
    
            var nom_proyectoParameter = nom_proyecto != null ?
                new ObjectParameter("nom_proyecto", nom_proyecto) :
                new ObjectParameter("nom_proyecto", typeof(string));
    
            var dir_proyectoParameter = dir_proyecto != null ?
                new ObjectParameter("dir_proyecto", dir_proyecto) :
                new ObjectParameter("dir_proyecto", typeof(string));
    
            var fecha_inicioParameter = fecha_inicio.HasValue ?
                new ObjectParameter("fecha_inicio", fecha_inicio) :
                new ObjectParameter("fecha_inicio", typeof(System.DateTime));
    
            var fecha_finParameter = fecha_fin.HasValue ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateProyecto", id_proyectoParameter, id_clienteParameter, id_divisionParameter, nom_proyectoParameter, dir_proyectoParameter, fecha_inicioParameter, fecha_finParameter);
        }
    
        public virtual ObjectResult<ListarPersonasDeInteresFull_Result> ListarPersonasDeInteresFull()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarPersonasDeInteresFull_Result>("ListarPersonasDeInteresFull");
        }
    
        public virtual ObjectResult<ListarPersonasALL_Result> ListarPersonasALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarPersonasALL_Result>("ListarPersonasALL");
        }
    
        public virtual ObjectResult<ListarTelefonosFull_Result> ListarTelefonosFull()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarTelefonosFull_Result>("ListarTelefonosFull");
        }
    
        public virtual ObjectResult<ListarTelefonosFullPorId_Result> ListarTelefonosFullPorId(Nullable<int> id_persona)
        {
            var id_personaParameter = id_persona.HasValue ?
                new ObjectParameter("id_persona", id_persona) :
                new ObjectParameter("id_persona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarTelefonosFullPorId_Result>("ListarTelefonosFullPorId", id_personaParameter);
        }
    
        public virtual int NewPerson(ObjectParameter newId)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NewPerson", newId);
        }
    
        public virtual ObjectResult<ListarEmailsFull_Result> ListarEmailsFull()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarEmailsFull_Result>("ListarEmailsFull");
        }
    
        public virtual ObjectResult<ListarEmailsFullPorId_Result> ListarEmailsFullPorId(Nullable<int> id_persona)
        {
            var id_personaParameter = id_persona.HasValue ?
                new ObjectParameter("id_persona", id_persona) :
                new ObjectParameter("id_persona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarEmailsFullPorId_Result>("ListarEmailsFullPorId", id_personaParameter);
        }
    }
}
