//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTA_DE_MATERIALES
    {
        public int id_documento { get; set; }
        public int proyecto { get; set; }
        public int pedido_por { get; set; }
        public Nullable<System.DateTime> fecha_pedida { get; set; }
        public Nullable<System.DateTime> fecha_aprobada { get; set; }
        public bool aprobado { get; set; }
        public int aprobado_por { get; set; }
        public int ingresado_por { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual PROYECTO PROYECTO1 { get; set; }
        public virtual EMPLEADO EMPLEADO1 { get; set; }
        public virtual EMPLEADO EMPLEADO2 { get; set; }
    }
}
