//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDEN()
        {
            this.DESPACHOes = new HashSet<DESPACHO>();
            this.DETALLE_DE_ORDEN = new HashSet<DETALLE_DE_ORDEN>();
        }
    
        public int id_orden { get; set; }
        public int id_proyecto { get; set; }
        public int id_cliente { get; set; }
        public int id_vendedor { get; set; }
        public bool factura { get; set; }
        public string notas { get; set; }
        public decimal sub_total { get; set; }
        public decimal total_igv { get; set; }
        public decimal total_venta { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual PROYECTO PROYECTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DESPACHO> DESPACHOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_DE_ORDEN> DETALLE_DE_ORDEN { get; set; }
    }
}
