//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANO
    {
        public int id_documento { get; set; }
        public int id_proyecto { get; set; }
        public string revision { get; set; }
        public int tipo_plano { get; set; }
        public int dibujado_por { get; set; }
        public int revisado_por { get; set; }
        public string nom_plano { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_revision { get; set; }
        public Nullable<System.DateTime> fecha_envio { get; set; }
        public string path_plano { get; set; }
    
        public virtual ID_DOCUMENTO ID_DOCUMENTO1 { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual PROYECTO PROYECTO { get; set; }
        public virtual PLANO_TIPO PLANO_TIPO { get; set; }
        public virtual EMPLEADO EMPLEADO1 { get; set; }
    }
}
