//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROVEEDOR()
        {
            this.ARTICULOes = new HashSet<ARTICULO>();
        }
    
        public int id_proveedor { get; set; }
        public Nullable<int> especialidad_proveedor { get; set; }
        public Nullable<byte> pais_proveedor { get; set; }
        public string nom_proveedor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICULO> ARTICULOes { get; set; }
        public virtual ESPECIALIDADES_PROV ESPECIALIDADES_PROV { get; set; }
        public virtual DIRECCION_PAIS DIRECCION_PAIS { get; set; }
    }
}
