//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALARIO
    {
        public int id_persona { get; set; }
        public int id_salario { get; set; }
        public decimal monto { get; set; }
        public byte frequencia_de_pago_dias { get; set; }
        public System.DateTime fecha_modificada { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
    }
}
