//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELEFONO
    {
        public int id_telefono { get; set; }
        public byte tipo_telefono { get; set; }
        public int id_persona { get; set; }
        public string codigo_pais { get; set; }
        public string campo_1 { get; set; }
        public string campo_2 { get; set; }
        public string campo_3 { get; set; }
        public string ext { get; set; }
    
        public virtual ID_PERSONA ID_PERSONA1 { get; set; }
        public virtual TELEFONOS_TIPOS TELEFONOS_TIPOS { get; set; }
    }
}
